### ISSUE TITLE
Choisir entre les tags et les champs personnalisés de projet

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#1002]
Clarifier l'usage labels vs tags de projet pour "priotiraire" "peu prioritaire". Choisir l'un des deux. 

![image](https://user-images.githubusercontent.com/1177762/234274734-aecb34bf-0965-4677-973c-4fd737a9e251.png)

Ça me semble difficile à lire ici, il faudrait être plus explicite.

**Comment by laem** [comment]
@lbranaa qu'en penses-tu ?

**Comment by lbranaa** [comment]
En l'occurence j'ai l'impression qu'ici ce sont deux labels --> l'un pour la priorité (de l'île à la montagne en feu), l'autre pour la taille (du hérisson à la baleine)

![Image](https://github.com/datagir/nosgestesclimat-site/assets/120486950/72d819d9-35b4-4f94-8d22-da0f7b6676f2)

En revanche ce serait cool qu'on soit plus clair sur comment on choisit les tags, les priorités, tailles et qu'on les systématise. Je regarde pour rajouter ça

**Comment by lbranaa** [comment]
Revue des labels en interne dans l'équipe, je ferme donc l'issue
