### ISSUE TITLE
Amélioration parcours action - améliorer les liens avec le modèle

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1021]
L'objectif est d'améliorer les actions proposées à l'utilisateur en fonction de son profil

- [ ] Vérifier qu'il ne reste pas d'incohérences (ex : on me propose de devenir végétarien alors que j'ai dit que je l'étais)
- [ ] Voir s'il y a des conditions à rajouter pour rendre les actions plus "intelligentes" --> exemple ici https://github.com/datagir/nosgestesclimat/issues/1045. C'est un travail de fond à faire en prenant en compte les issues existantes notamment dans le tag [écran action](https://github.com/datagir/nosgestesclimat/labels/parcours%20action)

**Comment by Benjamin-Boisserie-ABC** [comment]
Je me permets de faire le lien avec une issue ouvert avant que je parte en congé #1816
