### ISSUE TITLE
🐛 Impossible de saisie 0 si l'aide à la saisie `Avion` est ouverte

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat-site#1052]
> Depuis la page: `https://nosgestesclimat.fr/simulateur/bilan`
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by lbranaa** [comment]
Merci @Clemog ! c'est long à résoudre tu penses ?

**Comment by Clemog** [comment]
Non pas long, à monads une heure max

**Comment by Clemog** [comment]
Oui ! On a pas le même comportement que pour la voiture notamment

**Comment by jeannelf** [comment]
réparé en v2
