### ISSUE TITLE
⭐️ Rendre publiques nos stats "Northstar"

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1123]
Tout est dans le titre, en écrivant la release sur l'introduction des question northstar, il me semblait important de rendre les stats publiques

Je propose soit:
- D'ajouter une page `/northstar` sur NGC avec le dashboard metabase
- Ajouter l'un des graphes metabase dans notre page `/stats`

Ça semble assez simple, test ici :https://deploy-preview-1124--nosgestesclimat.netlify.app/northstar (https://github.com/datagir/nosgestesclimat-site/pull/1124) --> C'est long à s'afficher ...

Lien public: http://metabase-ngc.osc-fr1.scalingo.io/public/dashboard/0f6974c5-1254-47b4-b6d9-6e6f22a6faf7

iframe:

```
<iframe
    src="http://metabase-ngc.osc-fr1.scalingo.io/public/dashboard/0f6974c5-1254-47b4-b6d9-6e6f22a6faf7"
    frameborder="0"
    width="800"
    height="600"
    allowtransparency
></iframe>
```

**Comment by bjlaa** [comment]
Ne fonctionne pas en preview ! Mais bonne idée, j'ajouterai bien ça à la page stats mais c'est vrai que la différence de style risque de donner une créature de Frankeinstein pas ouf ! 🤔

**Comment by Clemog** [comment]
> Ne fonctionne pas en preview ! Mais bonne idée, j'ajouterai bien ça à la page stats mais c'est vrai que la différence de style risque de donner une créature de Frankeinstein pas ouf ! 🤔

Je crois que c'est parce que c'est looooong ..

**Comment by Clemog** [comment]
Normalement c'est bon !

**Comment by bjlaa** [comment]
Yes c'est trop cool ! Et est-ce qu'on n'ajouterait pas un petit message pour indiquer que le chargement des données peut prendre quelques minutes ?
