### ISSUE TITLE
Permettre de figer la région

### ISSUE THREAD

**Issue by trepmag** [incubateur-ademe/nosgestesclimat-site#1132]
Je fais suivre une demande de la ville de Genève pour une intégration du formulaire via iframe...

Voici le context: la page (ou site web) hôte qui contient l'iframe est contextualisé dans une région et invite ses visiteurs (de la région) à utiliser l'application. Dans ce cas, le choix de la région par le visiteur ou auto-détection n'a pas lieu, et au contraire pourrait porter confusion au visiteur...

On imagine que l'on pourrait fixer la région/language avec peut-être un paramètre d'url; e.g.:
```https://nosgestesclimat.fr/?local=fr_ch```

**Comment by Clemog** [comment]
Hello ! Normalement c'est bon, via #1304
