### ISSUE TITLE
Permettre l'application de communiquer ses dimensions à la page hôte (iframe)

### ISSUE THREAD

**Issue by trepmag** [incubateur-ademe/nosgestesclimat-site#1134]
Lorsque que l'application est intégrée dans un iframe, les potentiels doubles ascenseurs verticaux; elui de l'iframe + celui de la page hôte, pourrait faire venir à bout de nerfs même le plus expérimenté des Dalai Lama...

Une solution serait d'utiliser une libraire comme [iframe-resizer](https://davidjbradshaw.github.io/iframe-resizer/)...

**Comment by Clemog** [comment]
Idem, normalement c'est réglé dans https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1305
