### ISSUE TITLE
Corrections / retours pour Challenge tes amis

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1139]
Nous sommes en train de mettre en place une V1 de "Challenge tes amis", une nouvelle fonctionnalité qui a pour objectif de créer plus de viralité --> #1078 
L'objectif de cette issue est de provisionner un temps pour des retours / corrections, en lien avec @jeremiecook. Nous proposons 4 jours de provisionnement.

**Comment by bjlaa** [comment]
Je ferme cette issue car je travaille sur la même PR, on peut se contenter d'une carte je pense. J'ai repassé la première carte en `In progress` :)
