### ISSUE TITLE
Combiner simulation de groupe (conférence) et foyer

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#1151]
Je crois qu'une solution au problème incubateur-ademe/nosgestesclimat#113 peut / doit venir du mode conférence.

On aurait un certain nombre de questions qui seraient communes au groupe, donc remplies qu'une fois.

On pourrait donc voir un "profil foyer" que chaque membre devrait compléter avec ses réponses à lui. 

Avantages : 
- un "dashboard" famille qui permet de voir la répartition foyer / perso
- une clarification pour l'utilisateur de ce qui est son individu et ce qui est son foyer
- du temps gagné pour les autres membres de la famille

Par exemple, Anne fait une simulation NGC et se dit, "ah tiens c'est cool, faut que j'en parle à mon conjoint / à mes enfants". Elle pourrait accéder à un mode où la simulation qu'elle a déjà faite serait donc séparée en deux : foyer + individu.

**Comment by Clemog** [comment]
C'est fait @JuliePouliquen !

C'est même désormais encore plus proche de la fonctionnalité challenge

**Comment by JuliePouliquen** [comment]
Oh mais je savais pas ça ! Comme quoi je fais bien de dépiler les issues :smile:

**Comment by Clemog** [comment]
Non je voulais dire "C'est fait j'ai transféré côté site" 😅
