### ISSUE TITLE
Réparer la connexion à Metabase qui n'est plus possible

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1152]
Clément et moi n'arrivons plus à accéder à Metabase --> bug à investiguer (cf. capture d'écran pour le message d'erreur qui y est affiché)

![Capture d’écran 2023-06-26 à 13 48 37](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/120486950/5159945f-786b-4502-a017-ef04c4aa9224)

**Comment by Clemog** [comment]
Fix par la mise à jour de metabase
