### ISSUE TITLE
URL par question - undefined dans le titre

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1158]
<img width="901" alt="245807766-84145edd-1dea-4107-92c0-d9d0eac24d16" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/120486950/a759b719-2ec5-4e13-989d-4fc8773ffae3">

**Comment by EmileRolley** [comment]
Ne semble plus être d'actualité... A surveillé.
