### ISSUE TITLE
Améliorer l'affichage / UX / ancrage des questions dans la FAQ

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1161]
@Clemog, tu pourrais expliquer cette issue ? Merci beaucoup !

En lien avec #(https://github.com/incubateur-ademe/nosgestesclimat/issues/1943)

**Comment by dxb** [comment]
https://deploy-preview-1162--nosgestesclimat.netlify.app/contribuer#r%C3%A9seau-chaleur
