### ISSUE TITLE
"Notre serveur semble indisponible"

### ISSUE THREAD

**Issue by nosgestesclimat** [incubateur-ademe/nosgestesclimat-site#1163]
Apple Mac Os 12.6.6 -- Firefox 114.0.2 (64 bits)

Etape 3 - C'est parti = "Notre serveur semble indisponible"
> Ce ticket a été créé automatiquement par notre robot depuis notre [page de contribution](https://nosgestesclimat.fr/contribuer).

**Comment by Clemog** [comment]
C'est fixé normalement, il semble que Scalingo a eu un pb ce matin : https://scalingostatus.com/

**Comment by yako-san** [comment]
merci

**Comment by Clemog** [comment]
Merci pour les retours en tout cas ! :)

**Comment by yako-san** [comment]
Mais non, merci à vous. J’ai écouté Super Green Me (18 épisodes) en voyageant en voiture (pas de train :/ ) de Montréal à Caraquet. J’ai fait mon test et je suis en train de préparer une offensive dans mon réseau de « vrai.es » ami.es.Merci pour votre initiative —yako.xrLe 27 juin 2023 à 16:01, Clément ***@***.***> a écrit :﻿
Merci pour les retours en tout cas ! :)
