### ISSUE TITLE
V2 blog - possibilité de créer un encart de type "encadré"

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1185]
Dans le cadre de la V2 du blog (https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1137), l'objectif de cette issue est de donner la possibilité de créer un encart de type "encadré" : cadre de couleur + texte pour faire une mise en avant, ou un résumé en intro du blog.

**Comment by lbranaa** [comment]
@JuliePouliquen, je vois dans cet article https://nosgestesclimat.fr/blog/affichage-ges-transport qu'il y a des encadrés déjà --> tu pensais à quoi exactement de différent de ça ? Merci !

**Comment by JuliePouliquen** [comment]
Ça me paraît nickel pour le moment on peut clôturer :smile:
