### ISSUE TITLE
V2 blog - ajout de catégories

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1187]
Dans le cadre de la V2 du blog (https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1137), l'objectif de cette issue est de pouvoir ajouter des catégories

@JuliePouliquen, tu peux préciser les catégories / exemples de catégories auxquels tu penses ? Merci !

**Comment by JuliePouliquen** [comment]
Je pense aux catégories : releases, nouvelles études, vie du projet, réflexions... (les termes sont à définir)

**Comment by lbranaa** [comment]
Je ferme car pris en compte dans l'autre issue V2 blog
