### ISSUE TITLE
Rajouter un graph de synthèse dans la page stats

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1196]
Sur la page stats actuelle, avoir un graph qui permet de visualiser simplement 3 métriques clés : les visites, les simulations terminées, le nombre de mails collectés. Lié à la réalisation de #1193 

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/120486950/1b583e4a-8184-46c3-bec6-ec3282c4d57e)

**Comment by jeannelf** [comment]
on le fera dans metabase (si on y arrive hihi)

**Comment by jeannelf** [comment]
ouhla wtf
