### ISSUE TITLE
Image page d’accueil trop lourde / retirer le lazy loading sur l'image

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1200]
Implémenter la technique qui suit : charger une version pixelisée de l’image dans un premier temps, qui sera remplacée par l’image animée lorsqu’elle sera chargée à son tour. Permettra de faire d’une pierre deux coups : accélérer le chargement de la page, supprimer le layout shift induit par le chargement de l’image.

**Comment by florianpanchout** [comment]
À première vue : l'image semble être inline (et donc être chargée en même temps que le reste du dom) et attend le chargement et l'initialisation du script `AnimatedIllustration.chunk.js`. Peut être juste changer pour que l'image s'affiche (en statique) avant le chargement du script ?

**Comment by bjlaa** [comment]
Au final le poids de l'image en soi n'est pas le problème mais plutôt la manière dont elle était chargée, en lazy loading, et donc avec un délai, ce qui faisait se décaler le contenu de la page vers le bas, ce qui est pénalisé sur le plan du SEO.
