### ISSUE TITLE
Créer une page NosGestesClimat en .beta.gouv.fr

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1201]
C’est une suggestion de John ; créer une nouvelle page hébergée sur le serveur [[beta.gouv.fr](http://beta.gouv.fr/)](http://beta.gouv.fr) (contacter Julian Dauphant) > sous-domaine **[nosgestesclimat.beta.gouv.fr](http://nosgestesclimat.beta.gouv.fr/)**

L’idée ici est de profiter de l’aura du nom de domaine beta.[[gouv.fr](http://gouv.fr/)](http://[gouv.fr](http://gouv.fr/)). Les noms de domaines en [gouv.fr](http://gouv.fr/) sont extrêmement bien notés et référencés par les algos de référencement. Quand on héberge une page sur un site en gouv.fr qui comporte un lien dirigeant vers un site donné, ce site bénéficie en grande partie de cette aura et gagne en référencement.

Concrètement, il suffirait de :

1) demander à Julian Dauphant de nous créer le sous-domaine [[nosgestesclimat.beta.gouv.fr](http://nosgestesclimat.beta.gouv.fr/)](http://nosgestesclimat.beta.gouv.fr) ;

2) créer une page simple en html, résumant le projet, incluant un maximum de mots clés pertinents ainsi que (indispensable) un lien vers [nosgestesclimat.fr](http://nosgestesclimat.fr/)

3) uploader le fichier index.html sur le serveur et profiter !

**Comment by florianpanchout** [comment]
Demandes de création de sous-domaine faites pour nosgestesclimat.beta.gouv.fr et nosgestesclimat.ademe.fr

**Comment by JuliePouliquen** [comment]
Suite à l'appel passé avec John, l'idée est donc de partir sur des pages d'accueil dont nous allons revisiter les textes, avec des textes plus tournés vers : 

- "calculateur empreinte carbone" pour la page beta.gouv
- "bilan carbone" pour la page ADEME

J'écris les contenus à mon retour de congés, fin août.

**Comment by bjlaa** [comment]
Hého !
