### ISSUE TITLE
Bug - rajouter titre brique logement dans la documentation

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1208]
Quand on va dans la documentation, il manque le titre pour la partie logement

![Capture d’écran 2023-07-11 à 12 10 18](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/120486950/9ff973f2-573d-4a82-855d-7509a1b98a4f)

**Comment by Clemog** [comment]
Fix by https://github.com/incubateur-ademe/nosgestesclimat/commit/b65bbf969a4516c599260716d6f1d33cd0cd2d1c
