### ISSUE TITLE
Vérifier l'hébergement des images du blog

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#1220]
- [ ] Vérifier que les anciens articles sont pérennes (=les images toujours là) si on supprime le blog Datagir (ce qui va arriver)

- [ ] Si ce n'est pas le cas, le rendre pérenne

**Comment by florianpanchout** [comment]
@bjlaa À prendre en compte pour la nouvelle version du blog. Pour l'instant la grande majorité des images est hébergée ailleurs

**Comment by bjlaa** [comment]
Okay j'ai déjà ramené une partie des images en local, je m'occupe de rapatrier le reste
