### ISSUE TITLE
Nouveau format pour les URLs des questions

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#1225]
Page notion correspondante : https://www.notion.so/Arborescence-sitemap-et-URLs-00543a2beb9e4133a69d84655dc27de7

Il faut trancher sur le format des URLs dans `/simulateur` avant de les modifier en production.

**Comment by florianpanchout** [comment]
@jeannelf Je découvre cette issue et la reflexion associée. Le changement de Matomo (et la rupture possible avec l'historique) est peut être le bon moment pour mettre ça en place ?

**Comment by jeannelf** [comment]
carrément , il faudrait spécifier un peu mieux si on veut traiter ca au prochain sprint, je vais essayer de regarder pour comprendre mieux

**Comment by jeannelf** [comment]
transféré dans backlog notion  https://www.notion.so/accelerateur-transition-ecologique-ademe/URL-Architecture-cible-4bc958460f3b4b3299019831f322702c?pvs=4
