### ISSUE TITLE
Ré-activer le fait d'être redirigé vers une question spécifique via l'URL du test

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#1226]
## Contexte

Dans #1178, j'ai désactivé la possibilité de pouvoir être redirigé vers une question spécifique en spécifiant le nom de la règle correspondante dans le search param `question`. En effet, le search param `question` était à la fois utilisé pour spécifier une question spécifique directement dans un lien de partage comme pour passer à la question suivante du test lorsque l'utilisateur clique sur `Suivant`. Il était donc impossible de différencier l'utilisation d'une URL spécifique lorsque le test est terminé (voir #1159), du fais de cliquer sur `Suivant` après avoir répondu à la dernière question du test.

## Solution

Il faudrait donc différencier le search param utilisé pour naviguer entre les questions en cliquant sur les boutons du test, de celui utilisé pour spécifier le nom de la règle d'une question précise que l'on souhaite partager.

> Question : Cette fonctionnalité est-elle même réellement utile ? (Sinon, il faudra penser à supprimer les reliques de cette feature désactivée dans #1178 avant de fermer cette issue).

**Comment by jeannelf** [comment]
j'ai l'imrpssion que ca maintenant ca marche bien non?
en tout cas use case : j'ai déja fait le test > je retourne sur une url précise de question > je suis bien redirigée vers cette question la, avec ma réponse remplie
