### ISSUE TITLE
Mettre à jour l'empreinte dans les groupes "Challenge tes amis" lorsqu'on repasse le test

### ISSUE THREAD

**Issue by jeremiecook** [incubateur-ademe/nosgestesclimat-site#1237]
Actuellement, un groupe conserve le premier résultat de test disponible.
* Si l'on visite la page d'un groupe avant de passer le test, on se retrouve bloqué avec des valeurs par défaut
* Si l'on affine ses réponses, le résultat ne se met pas à jour sur le groupe

On devrait pouvoir modifier ses réponses, et repasser le test, et mettre automatiquement ses résultats à jour sur l'ensemble de ses groupes (en tant que créateur ou invité)

**Comment by florianpanchout** [comment]
@jeremiecook Corrigé ici : https://deploy-preview-1252--nosgestesclimat.netlify.app/

Les résultats du groupes se mettent à jour lorsque l'utilisateur visite le dashboard
