### ISSUE TITLE
Refonte / Vider le cache du navigateur en cas d'erreur de l'`engine` Publicodes

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1281]
Suite à https://www.notion.so/accelerateur-transition-ecologique-ademe/Bug-ferry-03-08-2023-0ed8b4a9134549a1965ef00f455ab862.

L'objectif est de permettre de vider le cache au refresh de la page -> aujourd'hui si une situation contient des valeurs qui cassent le moteur, on ne peut plus refaire de test sans vider son cache manuellement.

**Comment by EmileRolley** [comment]
Je pense que l'on devra raffiné le comportement avec la gestion des tests sauvegardés ainsi que la version du modèle utilisée (lorsqu'elle sera effective).

**Comment by florianpanchout** [comment]
À mettre en place sur la nouvelle version

**Comment by florianpanchout** [comment]
Dans la refonte on ne prends pas en compte les valeurs invalides de la situation. Est-ce que ça suffit pour régler le soucis ?

@Clemog

**Comment by Clemog** [comment]
Hum est ce qu'il n'y a pas un enjeu sur d'anciennes valeurs stockées dans la situation et dont la règle n'est plus utilisée mais quand même dans la situation du coup ?

Je m'éloigne un peu car je pense que le souci de cette issue est bien réglé via la refonte : je rentre une valeur à 0 pour une règle donnée qui est diviseur -> erreur donc je ne mets pas à jour la situation

**Comment by florianpanchout** [comment]
Ah non par contre si la règle est valide (donc dans ton exemple si publicodes accepte une valeur à zéro), on laisse faire (et donc ça va planter pareil).

Est-ce que le problème n'est pas à corriger côté Publicodes en améliorant la détection des valeurs interdites ?

**Comment by Clemog** [comment]
Aujourd'hui dans publicodes, il n'y a pas (je crois) de gestion des valeurs interdites. On le gère "à la main" pour la question des voyageurs et habitants avec les notifications notamment.

L'idée de cette issue c'est pour répondre au cas du bug du ferry : on affichait une question qui ne devait pas l'être et dont la réponse ne devait pas être 0. La réponse à 0 était donc intégrée dans la situation et le moteur cassait. Impossible de reprendre le test même avec un F5..

**Comment by Clemog** [comment]
https://www.notion.so/accelerateur-transition-ecologique-ademe/Bug-ferry-03-08-2023-0ed8b4a9134549a1965ef00f455ab862

**Comment by florianpanchout** [comment]
Mais du coup est-ce que ça ne serait pas plus simple d'ajouter des valeurs interdites dans Publicodes ? Avoir un min et un max possible pour chaque valeur numérique me semblerait être une bonne première étape. Comme ça le setSituation planterait et on pourrait réagir plus facilement ensuite

**Comment by Clemog** [comment]
> Mais du coup est-ce que ça ne serait pas plus simple d'ajouter des valeurs interdites dans Publicodes ? Avoir un min et un max possible pour chaque valeur numérique me semblerait être une bonne première étape. Comme ça le setSituation planterait et on pourrait réagir plus facilement ensuite

Il y a bien un sujet sur les "bornes" acceptables : https://github.com/incubateur-ademe/nosgestesclimat/issues/2080

**Comment by florianpanchout** [comment]
Si ça vous va (@jeannelf et @Clemog), vu la faible prévalence du problème je propose de le régler directement côté Publicodes avec la création de bornes

**Comment by jeannelf** [comment]
ok pour moi en attendant, mais peut etre qu'il faudrait recréer une issue poru traiter le sujet de façon plus "propre" plus tard ?

**Comment by florianpanchout** [comment]
Vu ensemble aujourd'hui : on ne traite pas ce sujet côté front pour l'instant (mais côté Publicodes via https://github.com/incubateur-ademe/nosgestesclimat/issues/2080)

**Comment by jeannelf** [comment]
on supprime l'issue du coup ?

**Comment by Clemog** [comment]
Pour moi c'est pas résolu

**Comment by jeannelf** [comment]
je vois pas comment tester ce bail @florianpanchout

**Comment by florianpanchout** [comment]
Y'a rien a testé on a dit qu'on ne le traitait pas côté front pour l'instant

**Comment by Clemog** [comment]
Pas vraiment besoin de tester puisqu'on acte qu'on ne gère pas la situation côté site mais on a pas encore résolu le fait que si certaines valeurs "interdites" sont rentrées, le site casse et l'utilisateur ne peut plus faire de simulation sans vider le local storage

**Comment by Clemog** [comment]
Lié en partie mais je pense qu'on doit en faire une nouvelle issue: 

Le fonctionnement actuel pour les valeurs interdites en prod n'est pas retranscrit dans la refonte (question nombre de voyageurs dans la voiture + question nombre d'habitants dans la logement)
