### ISSUE TITLE
Créer un groupe d'amis : bouton créer et passer le test ne fonctionne pas

### ISSUE THREAD

**Issue by twalter23** [incubateur-ademe/nosgestesclimat-site#1308]
## Le bouton créer et passer mon test de la sous-page "Créer un groupe d'amis"ne fonctionne pas : rien ne se passe lorsqu'on clique.

![image](https://github.com/incubateur-ademe/nosgestesclimat/assets/114344089/adab2b9f-62de-4f60-8808-20f244600bd2)

Testé sous firefox 117.0.1 et chrome 116.0.5845.188 (Build officiel) (64 bits)

**Comment by bjlaa** [comment]
Bonjour et merci pour votre retour !

Nous avons effectivement constaté un problème, lorsque le formulaire était rempli en faisant usage de la fonctionnalité d'auto-complétion du navigateur. Un correctif a été mis en place.

Aviez-vous fait usage de cette fonctionnalité avant de cliquer sur le bouton ?

**Comment by twalter23** [comment]
Bonjour,
Avec plaisir. 
Il me semble en effet que j'ai utilisé l'auto-complete (certitude de 95%). 
Cela semble fonctionner, je vais pouvoir challenger mes amis sur leur empreinte. 
Merci pour votre travail en tout cas !

**Comment by bjlaa** [comment]
Bonjour, 

Ah super nouvelle ! Oui, l'auto-complete a été désactivé pour le moment de manière temporaire, le temps que nous trouvions ce qui cause le problème sur le formulaire :)

Merci et bonne continuation !
