### ISSUE TITLE
Bug utilisation du mode groupe

### ISSUE THREAD

**Issue by JuliePouliquen** [incubateur-ademe/nosgestesclimat-site#1314]
Reçu par email de Anne-Sophie Denis

Bonjour,

J'ai une question sur l'utilisation du mode sondage, nous sommes plusieurs à avoir réalisé le test mais je ne vois que mes résultats dans le mode sondage. Nous apparaissons bien tous dans le classement. Comment faire pour que les autres membres du groupe apparaissent dans le sondage, ils ont pourtant bien fait la simulation. Nous avons dû passer à côté de quelque chose.  Je vous remercie de votre aide.

**Comment by bjlaa** [comment]
C'est le fonctionnement actuel du nouveau mode groupe : chaque participant voit dans son navigateur le classement de chacun des participants ainsi que le détail par catégorie d'émissions de sa propre empreinte. En revanche, les participants ne peuvent pas accéder au détail par catégorie des autres participants.

À confirmer avec la dame car je suis pas certain d'avoir bien compris son problème. 🤔

**Comment by JuliePouliquen** [comment]
Je lui ai répondu, je verrai s'il y a de nouveaux retours. Je me permets de pinguer @jeremiecook car il me semble que ça touche au design.

**Comment by JuliePouliquen** [comment]
@jeremiecook je clôture car la dame confirme que c'est bien ça qu'elle entendait et a compris que c'était le fonctionnement actuel. Peux-tu l'ajouter au Notion ?
