### ISSUE TITLE
Refonte / Modifier le site actuel pour ne gérer que Sondage/Conf

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1316]
Modifier le site existant (sur une branche à part) pour qu’il ne gère que la partie sondage / conférence. Cela afin de pouvoir linker vers cette branche depuis la refonte. 

Reflexion tech à avoir : la partie sondage / conf (https://nosgestesclimat.fr/groupe) n'a pas été refondue, donc la v1 de la refonte devra rediriger vers l'aancien front de ces pages.
Questions : 
- est-ce qu'on peut garder un url unique ngc.fr 
- ou doit on créer un autre url type sondage.ngc.fr ? 
- si oui comment ca marche?

**Comment by jeannelf** [comment]
Sujet à discuter avec @jeremiecook : comment on fait comprendre aux gens qpq ils sont sur un nouvel URL

**Comment by bjlaa** [comment]
- nouveau projet sur netlify
- créer sous-domaine sur Gandi : sous-domaine `sondages.nosgestesclimat.fr`
- modifier l'app pour qu'il ne reste qu'un seul bouton vers le mode sondage
- retirer / modifier les liens internes pour verrouiller l'utilisateur dans le mode sondage

**Comment by bjlaa** [comment]
@jeannelf @jeremiecook on la la version du site V1 avec les sondages/conférences en mode standalone à recetter ici : https://sondages.nosgestesclimat.fr.
Les liens côté site V2 sont modifiés par cette PR : https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/56

**Comment by jeannelf** [comment]
Pour l'instant l'URL qui est sur preprod c'est "sondage" alorsq ue votre url de test c'est "sondageS" mais c'est peut etre normal
<img width="837" alt="Capture d’écran 2023-10-03 à 10 37 56" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/bab37b4e-8a7c-449b-b059-c51b4dac9db5">
<img width="1141" alt="Capture d’écran 2023-10-03 à 10 37 54" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/22f1b352-e51c-4d92-ac28-2eb674ec88d2">

**Comment by jeannelf** [comment]
Deuxieme chose : 
- j'essaie de créer un sondage : serveur indisponible
<img width="980" alt="Capture d’écran 2023-10-03 à 10 39 02" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/cca20d0a-d882-474e-8ae1-a27622113d86">

- conférence => ok

**Comment by bjlaa** [comment]
Oups, oubli de ma part 🙈  Je viens de modifier les URLs acceptées côté serveur pour qu'il accepte les requêtes de sondages.nosgestesclimat.fr.

Concernant le lien côté preprod, je n'avais pas encore mergé ma branche qui le modifiait, normalement on est tout bons là ! 🙂

**Comment by jeannelf** [comment]
yesss pour moi cest ok c'est iso avec la prod il me semble, mais peut etre petite confirmation de @Clemog

**Comment by Clemog** [comment]
J'ai testé rapidement mais j'ai l'impression que c'est bon aussi !
On a bien accès aux anciens sondages ?

**Comment by bjlaa** [comment]
Aurais-tu l'URL d'un ancien sondage ?

**Comment by Clemog** [comment]
Par exemple : Grand-sondage-universités-2022
