### ISSUE TITLE
Refonte / Ajout de Tests E2E + snapshots

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1317]
Ajouter des tests e2e pour avoir une couverture complète du site, et s’assurer qu’ils passent. 
Les tests indispensables à avoir pour cette v0

Page d'accueil : 
- [ ] la page s'affiche
- [ ] le CTA de démarrage apparaît bien sur la page d'accueil
- [ ] on peut passer les pages du tuto et/ou faire le tuto (suivant ou passer)

Simulateur :  
- [ ] chaque persona peut passer le test

Challenge tes amis : 
- [ ] la page s'affiche
- [ ] on peut créer un groupe
- [ ] le résultat se modifie quand quelqu'un a fait le test (à passer plus tard si jamais cest trop complexxx)

**Comment by jeannelf** [comment]
@florianpanchout ca te va comme premiere liste un peu high level sur les trucs à mettre en tests e2e?

**Comment by florianpanchout** [comment]
Ça me semble bien (et j'ai l'impression que c'est déjà couvert en prod).

Je rajouterais : 
-  [ ] mettre en place [Cypress Snapshot](https://github.com/meinaart/cypress-plugin-snapshots) (ou équivalent) pour avoir la liste exhaustive des pages affectées par une PR

**Comment by florianpanchout** [comment]
Et petit cadeau : 

- [ ] Ajouter des tests via [Browsterstack](https://www.browserstack.com/docs/automate/cypress) pour s'éviter d'avoir à tester sur toutes les config possibles à chaque fois

**Comment by bjlaa** [comment]
> Et petit cadeau :
> Ajouter des tests via [Browsterstack](https://www.browserstack.com/docs/automate/cypress) pour s'éviter d'avoir à tester sur toutes les config possibles à chaque fois

À mettre dans une nouvelle carte ? :)

**Comment by florianpanchout** [comment]
Yep, ainsi que 

> Je rajouterais :
> 
> * [ ]  mettre en place [Cypress Snapshot](https://github.com/meinaart/cypress-plugin-snapshots) (ou équivalent) pour avoir la liste exhaustive des pages affectées par une PR

**Comment by florianpanchout** [comment]
...et qui en fait quoi ?

**Comment by bjlaa** [comment]
Ça me paraissait curieux à moi aussi, je me suis imaginé que tu voulais pouvoir checker à la mano 🤔

**Comment by jeannelf** [comment]
@florianpanchout je peux tester quoi en fonctionnel la ? rien non ? 
J'ai créé une nouvelle carte notion avec les 2 points manquants : https://www.notion.so/accelerateur-transition-ecologique-ademe/Refonte-Test-e2e-fin-91817ecb8c914a3297b8f3fa8a8debd0?pvs=4

**Comment by florianpanchout** [comment]
Nope rien a tester de ton côté
