### ISSUE TITLE
Refonte / Mise en place d'une branche de Preprod

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1319]
Par ex déroulé
- develop/preprod = branche par défaut => tout se merge la (nom à décider)
- prod

**Comment by florianpanchout** [comment]
Qu'est ce que l'on souhaite comme nom pour cette branche ?

- staging 
- preprod
- [develop](https://www.atlassian.com/fr/git/tutorials/comparing-workflows/gitflow-workflow)

**Comment by florianpanchout** [comment]
Environnement de preprod visible ici : https://preprod.nosgestesclimat.fr/. C'est la que tout se recettera à partir de maintenant

La branche `preprod` est maintenant la branche par défaut du repo.

**Comment by jeannelf** [comment]
donc ca y est je teste sur preprod?? 🤩

**Comment by florianpanchout** [comment]
Welcome to the future
