### ISSUE TITLE
Refonte / Bug 🪲 / Lien changement de langue

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1320]
Le lien de changement de langue (vers langue anglaise) fait péter la page d'accueil)

**Comment by jeannelf** [comment]
Démo ci dessous : 
- quand on clique dessus ca marche pas
- en plus le lien de retour de la 404 ne marche pas non plus (pb trad?)
- mais quand on refresh l'URL ou qu'on pointe directement sur cet URL ca marche 

https://www.loom.com/share/b0409c0596a24eada1b2c804a9e93227?sid=96751435-a722-4907-b61c-37f6753a0e78

**Comment by florianpanchout** [comment]
⚠️ L'url n'est plus "en-US" mais "en" (on peut remettre "en-US" mais je doute de la pertinence de la chose)

**Comment by jeannelf** [comment]
non en effet laissons en, nickel
