### ISSUE TITLE
Refonte / Partage / Ajout metadata et image partage

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1321]
ajout des metadata
génération de l'image de partage (opengraph)

**Comment by bjlaa** [comment]
Oui c'est sensé être déjà le cas ! Il y a une génération d'image pour chaque slide de la page de fin. On avait déjà ça côté site actuel, marche pô pour le moment, j'ai créé une issue à ce sujet : https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1356
