### ISSUE TITLE
Refonte / Amélio comportement "Terminer"

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1323]
Réduire le délai lorsque l’on clique sur “Terminer” sur la dernière question

**Comment by jeannelf** [comment]
@florianpanchout c'était dans les trucs que tu m'avais mis dansta liste du jour mais cest peut etre à supprimer ?

**Comment by florianpanchout** [comment]
Non non c'est le prochain item dans ma todo

**Comment by jeannelf** [comment]
niveau test ici @florianpanchout pas grand chose de visible de mon côté, si ?

**Comment by florianpanchout** [comment]
La page de fin s'affiche 500ms plus rapidement. Donc bof à tester oui
