### ISSUE TITLE
Refonte / Mettre à jour l'url selon la slide active sur l'écran de fin 

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1327]
Mettre à jour le query params `diapo` lorsque l'on change de slide sur l'écran de fin. Afin de pouvoir tracker le nombre de vues sur chaque écran.

**Comment by jeannelf** [comment]
pas testable non? la j'ai testé ca n'a pas changé d'url

**Comment by florianpanchout** [comment]
C'est encore sur la PR (j'ai mis toutes mes PR en attente de code review dans "To Review", je ne sais pas si c'est la chose à faire)

**Comment by jeannelf** [comment]
Je me demande si ca ne va pas poser probleme niveau stats : 
- quand on arrive sur sa page de bilan pour la premiere fois (slide 1), on n'a pas d'attribut correspondant à la slide dans l'URL
- quand on change de slide vers 2 ou 3, il y a bien des attributs
- quand on revient ensuite à la slide 1, on a alors un attribut, on a donc 2 URL différents pour la meme page



=> ne peut on pas ajouter directement l'attribut à la slide 1 comme ca on a tjs le mm url @florianpanchout ?
