### ISSUE TITLE
Refonte / Page conclusion quelques retouches

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1329]
- [ ] Résultat : clic sur le ℹ️ = erreur
au clic sur le i, 

<img width="300" alt="Capture d’écran 2023-09-27 à 17 41 31" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/53f1f881-5c99-43c8-b044-b849c398b454">

ca ouvre bien unn ouvel onglet cette fois mais on arrive ici,

<img width="600" alt="Capture d’écran 2023-09-27 à 17 41 38" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/24df52c8-1a60-47ba-a8e0-552b59e571fe">

- [ ] Dépôt d'email : 
A fonctionné pendant un temps puis m'a fait une erreur 500 : 

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/c45a2ec1-4d1a-4cfa-8406-90d86d926117)

**Comment by florianpanchout** [comment]
Le dépot d'email devrait être corrigé par https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/36 

Et le point 1 est lié à https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1330 il me semble
