### ISSUE TITLE
Refonte / Bug / Liens externes mal gérés

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1330]
- [ ] liens dans les Notes et détails des calculs
- cible = comme en prod : ouvre dans un nouvel onglet + renvoie vers lien valide - voir [notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Sept-23-Recettage-refonte-6a2dd05211e14c0fb78e32f1b4abc520?pvs=4#c434d0841d1043f6bbce518e61f41d30)
- bug aujourd’hui en test : charge sur l'onglet en cours et lien ne marche jamais- voir [notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Sept-23-Recettage-refonte-6a2dd05211e14c0fb78e32f1b4abc520?pvs=4#c434d0841d1043f6bbce518e61f41d30)
        
- [ ] comportement dans les actions détaillées
- pas d'ouverture dans nouvel onglet no plus
- liens semblent transformer, par ex sur la page gaspi alimentaire un "/" est rajouté en fin de lien et le fait bugger
- et en général tous les liens sont du format https://nosgestesclimat.vercel.app/https://librairie.ademe.fr/consommer-autrement/1947-manger-mieux-gaspiller-moins-9791029708480.html et ca renvoie vers
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/a98de24c-e52b-4e5a-8a20-d0edb10da1d2)

**Comment by jeannelf** [comment]
c'est testable @florianpanchout ? car j'ai retrouvé le bug a plusieurs endroits, jespere quil faut pas checker lien par lien 💀

**Comment by florianpanchout** [comment]
[Pareil qu'ici](https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1327#issuecomment-1737918073). La PR est en attente de code review pour merge
