### ISSUE TITLE
Refonte / Bug / retour en boucle à une question

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1331]
je suis dans alimentation, je reponds à la question “repas”, suivant ⇒ et j’arrive sur  alors que j’avais déjà repondu (on voit d’ialleurs que c’est deja sélectionné) , et on me fait repasser toute sles questions transport

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/188ed208-ea5f-4846-b637-c7ff4b5e66e5)

meme bug réapparu à la fin de divers, on me renvoie encore vers cette meme question, et là on me fait refaire TOUT LE TEST avec mes rep pré remplies mais i wanna die 💀

**Comment by florianpanchout** [comment]
n.b : le bug était reproductible en cliquant sur une suggestion qui updatait plusieurs réponses (comme pour les repas ou les boissons chaudes) puis en faisant suivant.

**Comment by jeannelf** [comment]
top ca me semble all good
je passe en done

**Comment by jeannelf** [comment]
j'ai bougé dans une (encore) nouvelle colonne pcq cest pas done en prod @florianpanchout tu me dis si cest ok pour toi comme process ?

**Comment by florianpanchout** [comment]
Ça me va ; mais à terme ça devrait pas être juste dans "Awaiting release" ? Une fois que l'on aura fais notre "fake release des trucs déjà en prod"

**Comment by jeannelf** [comment]
yes mais tnat qu'on a une partie qui va etre mergée direct en prod et une partie qui attend la branche de prepod je prefere avoir ca si cest okeyyyy
