### ISSUE TITLE
Refonte / Bug modèle calcul / Résultat différent prod test

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1332]
Parfois, les memes réponses donnent un résultat différent en prod et en test
Par exemple

- Logement / cb de personnes vivent chez vous
        - v1 j’ai +187
        - et v2 autre chose mais moins

- Logement / Appartement 
        - v1 : -180kg
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/94f59f8c-fb49-4f9a-b02f-1f7a5fd04c53)
        - v2 : -207kg
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/fbc3be5c-6356-4674-af41-ac9bf0169d3d)

**Comment by florianpanchout** [comment]
On a une différence sur la valeur de bilan dès le début du test en fait : 
- 8575.742319956033 sur la prod
- 8618.613786933493 sur la refonte

@Clemog une idée d'ou ça peut venir ? Tout ce qu'on fait c'est [initialiser un engine ici](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/blob/55c9e5da1dba47424203ceb3f6b1e67ec1b1d40f/src/publicodes-state/simulationProvider/useEngine.ts#L14) avec [des rules récupérées ici](https://data.nosgestesclimat.fr/co2-model.FR-lang.fr-opti.json)

**Comment by Clemog** [comment]
Hum j'ai bien 8618 en prod de mon côté 
<img width="905" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/55186402/7ab25b23-7a16-4838-a4c1-c9783d07e2c9">

**Comment by Clemog** [comment]
Au passage (je ferai une review dans l'endroit adapté dès que possible) :

- Ne pas avoir le clic pour accéder à une catégorie c'est assez pénible
- On ne peut plus répondre "Je ne sais pas" via escap ce qui était hyper pratique

**Comment by Clemog** [comment]
Je viens de faire le test de tes points précis @jeannelf, je ne dois pas avoir les mêmes entrées que toi mais j'ai effectivement des différences dans les différences affichées lors du choix de réponses (malgré un total identique), il y a peut etre qque chose à ce niveau là
D'ailleurs j'ai bien les "+ xxx" mais pas les "- xxx" sur la refonte

**Comment by jeannelf** [comment]
@Clemog 

> * Ne pas avoir le clic pour accéder à une catégorie c'est assez pénible
Agree mais apparemment très complexe (cf comm de florian sur le [notion](https://mattermost.incubateur.net/betagouv/pl/bqutm4pxb7nxzcz3ud5w6y4fsa)) 
> * On ne peut plus répondre "Je ne sais pas" via escap ce qui était hyper pratique
On peut avec ENTER
> D'ailleurs j'ai bien les "+ xxx" mais pas les "- xxx" sur la refonte
Ils y sont bien de mon côté mais 
- peut etre pas toujours ? @florianpanchout 
- beauuuucoup trop rapide cf un autre point mentionné dans le notion

**Comment by florianpanchout** [comment]
### Pour la différence sur la question appartement (et j'imagine les autres) :

J'ai bien les mêmes valeurs en prod et sur refonte (j'avais testé la prod en local qui me donnait une autre réponse) : 

- Situation vierge : 8618.613786933493 
- Situation avec appartement = oui : 8430.036981983143 

Ce qui donne une différence de 188.576805 (que l'on arrondit 188.6). Je ne sais pas d'ou la prod sort son chiffre

### Pour l'affichage de la différence

Pour être honnête c'est un truc que j'ai codé vite fait au début et que j'ai oublié de retoucher ensuite (avec un peu de chance ça passait...). Donc pour l'instant on attends genre 1s avant de réinitialiser la valeur de comparaison (donc si pendant cette seconde on fait +100 puis -100, ça affiche 0, donc rien)

**Comment by florianpanchout** [comment]
Je ferme l'issue ; le bug semblant être sur la prod et pas sur la refonte.
