### ISSUE TITLE
Refonte / Responsive dernières amélio

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1334]
En responsive mode : 

-[ ] Le footer n'est pas toujours fixé, par exemple sur la page profil

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/6712980a-6161-4eee-8516-5b4a91f4d5ae)

- [ ] Les alignements sont un peu moches

  - v1 (goal)
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/1e72b36f-4cc8-4cf5-9529-1b2ec6238df4)

 
  - v2 
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/65e3b3f3-f29b-4ed2-a0bb-85035bc27bf1)

**Comment by florianpanchout** [comment]
@bjlaa C'est lié à quelle PR ?

**Comment by bjlaa** [comment]
@florianpanchout mis à jour

**Comment by jeannelf** [comment]
@bjlaa je vois toujours pas le footer de mon côté

**Comment by bjlaa** [comment]
Le build a fail côté vercel, ce qui fait que les dernières modifs n'apparaissent pas sur la preview. Je regarde !

**Comment by jeannelf** [comment]
en fait sur preprod ca semble bon !

**Comment by bjlaa** [comment]
Chelou j'ai pas encore mergé 😅

**Comment by jeannelf** [comment]
ah bon alors pardon je me tais

**Comment by bjlaa** [comment]
en vrai il me semble qu'il s'affichait correctement parfois et d'autres fois non, tu n'es pas dingo ! Le correctif vient harmoniser ce comportement
