### ISSUE TITLE
Refonte / Bug différence d'état test / accueil

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1336]
La home m’invite à reprendre mon test, la page profil à le commencer. C’est cassé également sur la page Agir qui propose de “passer le test”. 

####Comportement actuel : 

Trois libellés différents pour la même action, selon les endroits : 

- page d'accueil
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/7262a72d-efc1-47ec-a0f6-5201dcb27c34)

- profil
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/8505d2d5-282f-4fa9-8786-23447d0aaf9c)

- page action
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/beff4fce-5cdc-494c-b289-eabeb79fb6d0)

####Comportement souhaité : 

Le texte doit être le meme dans ces trois endroits SAUF si on a déjà fini le test, ca donne : 

- [ ] Page d'accueil
 - Je n'ai pas commencé le test : "Faire le test"
 - J'ai un test en cours : "Reprendre mon test"
 - J'ai fini le test : "Voir mes résultats"

- [ ] Profil
 - Je n'ai pas commencé le test  : "Faire le test"
 - J'ai un test en cours : "Reprendre mon test"
 - J'ai fini le test : "Recommencer le test"

- [ ] Page actions 
 - Je n'ai pas commencé le test  : "Faire le test"
 - J'ai un test en cours : "Reprendre mon test"
 - J'ai fini le test : rien puisqu'on ne voit pas cette image, la page actions étant affichée

**Comment by florianpanchout** [comment]
Comment on détermine un test en cours ? 

1. Tutoriel affiché ?
2. Première question affichée ?
3. Première question répondue ?

**Comment by jeannelf** [comment]
3e reponse

**Comment by florianpanchout** [comment]
Est-ce que c'est ok si la home garde "Reprendre mon test" même une fois le test complété ? Deux raisons : 
- On arrive pas directement sur la page de résultat mais sur l'étoile moche
- Ça demande de rapatrier des informations en plus dans l'objet user (ce qui est une bonne idée en soit et pourra être fait par la suite mais demande un peu de temps (1/2 journée à 1 journée) pour le faire bien)

**Comment by jeannelf** [comment]
yes aucun souci go pour ca
