### ISSUE TITLE
L'iframe ne charge pas dans safari

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1337]
Je remonte un bug déjà identifié plusieurs fois.. En prod l'iframe ne charge pas sur Safari...

Aujourd'hui, il est possible d'intégrer l'iframe en direct (on peut pas faire grand chose) ou via un script qui utiliser https://github.com/incubateur-ademe/nosgestesclimat-site/blob/master/source/sites/publicodes/iframe.js ou https://github.com/incubateur-ademe/nosgestesclimat-site/blob/master/source/sites/publicodes/iframeSimulation.js

Pour tester (nav privée):

- https://nosgestesclimat.ch (iframeSimulation.js)
- https://bonpote.com/comment-calculer-son-empreinte-carbone (iframe.js)

**Comment by jeannelf** [comment]
Pour moi
- ✅ iframe.js : marche sur bonpote
- 🚫 iframeSimulation.js : blank sur ch 

Mais si ca se résout en Next comme le dit Florian, autant attendre 10 jours que ce soit live
Par contre @florianpanchout comment peut on s'en assurer niveau test?

**Comment by florianpanchout** [comment]
Via les urls de tests : 
- https://nosgestesclimat.vercel.app/demo-iframe
- https://nosgestesclimat.vercel.app/demo-iframeSimulation

**Comment by Clemog** [comment]
> Via les urls de tests :

Yes mais de mon côté, il me semble que ça fonctionne bien sur l'url de test 🤔

**Comment by jeannelf** [comment]
moi aussi ca fonctionne sur les tests nextJS, quel est le souci du coup ? ca veut pas juste dire que la refonte regle le pb?

**Comment by florianpanchout** [comment]
Visiblement l'url de test de la prod actuelle fonctionne aussi sur Safari. Donc le problème vient (probablement) du script qui génère l'iframe.

Vu que l'on reprends ce script à l'identique sur la refonte, peu de chance de corriger le bug. Ça demandera un travail supplémentaire d'investigation

**Comment by jeannelf** [comment]
moi j'ai bein un souci sur l'URL de prod sur l'écran suisse mais pas sur l'autre

**Comment by bjlaa** [comment]
Étrange, je pense pas avoir beaucoup modifié `iframeSimulation.js` côté refonte 🤔 ça vaut le coup de jeter un oeil et comparer. Je peux m'en occuper en début d'aprèm

**Comment by jeannelf** [comment]
non pardon je sais pas si c'était clair @bjlaa, de mon côté sur safari cest 

En prod
✅ iframe.js : marche sur bonpote
🚫 iframeSimulation.js : blank sur ch

Sur Vercel
✅ iframe.js 
✅ iframeSimulation.js

**Comment by florianpanchout** [comment]
Ok donc le problème a été corrigé via https://github.com/incubateur-ademe/nosgestesclimat-site/pull/1312 et la Suisse tape sur une PR (qui n'a pas le correctif) plutôt que sur la prod

**Comment by Clemog** [comment]
Hum pardon de revenir sur cette issue mais il me semble que l'URL suisse tape bien sur master côté site normalement ?

**Comment by Clemog** [comment]
Ouuups my bad, je tape bien ici : https://deploy-preview-1302--nosgestesclimat.netlify.app

Ce qui n'a aucun sens, c'est une erreur de mon côté

**Comment by florianpanchout** [comment]
Sauf si tu as la main sur leur html, mais eux ils appellent le script via `https://deploy-preview-1302--nosgestesclimat.netlify.app/iframeSimulation.js`

**Comment by florianpanchout** [comment]
Je déplace dans Awaiting response vu que c'est à la Suisse de corriger

**Comment by jeannelf** [comment]
a force de jamais prendre parti...
