### ISSUE TITLE
Refonte / Ajout d'un process simple pour travailler sur le modèle

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1338]

**Comment by florianpanchout** [comment]
Lié a https://github.com/incubateur-ademe/nosgestesclimat/pull/2081.

**Comment by jeannelf** [comment]
j'ai rien à tester ici @florianpanchout ?

**Comment by florianpanchout** [comment]
Nope c'est juste un outil de dev pour Clément et Julie ; donc à faire évoluer selon leurs retours lorsqu'ils auront eu le temps de regarder
