### ISSUE TITLE
Refonte / Triple tracking de la page d'entrée

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1340]
La page d'entrée du site semble envoyer 3 pageview à Matomo.

**Comment by florianpanchout** [comment]
1er pageview supprimé par @bjlaa [ici](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/pull/41).

3eme pageview présent seulement en dev (le layout est chargé deux fois en strict mode)

**Comment by jeannelf** [comment]
ca me semble en effet bon chez moi
