### ISSUE TITLE
Ne pas tracker /simulation/bilan

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1342]
Lorsque l'on arrive sur le simulateur, on arrive sur l'url "/simulateur/bilan". Puis on génère le formulaire ce qui permet de determiner la question à afficher. Puis on change l'url pour refleter la question affichée.

Actuellement on track 2 pages : "/simulateur/bilan" et "/simulateur/bilan?question=nom_question"

Il faudrait ne tracker que la deuxième ("/simulateur/bilan?question=nom_question")

**Comment by jeannelf** [comment]
pourquoi on ne trackerait pas ? 
c'est bien de savoir quand les gens arrivent sur la page et si ils droppent ici non (ce qui est le cas)


![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/29392fd5-b9b6-419c-8915-6b833f05a353)

**Comment by florianpanchout** [comment]
`simulateur/bilan` se transforme automatiquement en `/simulateur/bilan?question=nom_question` (donc impossible de quitter sur `simulateur/bilan` à moins d'être très rapide)

**Comment by jeannelf** [comment]
ah oui en effet, comment se fait il qu'on ait aautant de sorties mappées sur cet URL alors ? ca parait peu probable, cest mal tracké ?

**Comment by florianpanchout** [comment]
Très bon point : c'est le temps que le modèle charge. Donc il faut garder cet indicateur.

À noter qu'il y a une différence de comportement entre la prod et la refonte :  sur la prod, le modèle doit être chargé avant d'afficher le tutoriel, ce qui donne le déroulé suivant : 
- url `/simulateur/bilan`=> affichage loader
- url `/tutoriel` => affichage loader
- url `/tutoriel`=> affichage tutoriel

Alors que sur la refonte le modèle charge en fond pendant l'affichage du tutoriel. Ce qui fait qu'un utilisateur qui arrive pour la première fois a de forte chance de ne pas voir le loader du tout

**Comment by jeannelf** [comment]
ok donc on confirme qu'on ne laisse pas cet url en refonte, en revnache il est pertinent pour comprendre le tps d'attente en prod

**Comment by florianpanchout** [comment]
Si on en a besoin en refonte aussi, vu que c'est le seul moyen de tracker si l'utilisateur quitte pendant l'affichage du loader (qui devrait être fortement réduit mais quand même pas inexistant)

**Comment by jeannelf** [comment]
okeyz
