### ISSUE TITLE
Refonte / Affichage de changement de score à améliorer

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1343]
L'affichage du changement de score ("+ 121 kg CO2e" par exemple) ne reste pas assez longtemps et gagnerait à être animé

**Comment by jeannelf** [comment]
ah bah tu m'étonnes si tu crées des cartes dans mon dos le vendredi psss

**Comment by jeannelf** [comment]
c parfé
