### ISSUE TITLE
Refonte / Design / Passage des catégories : comment le signaler ?

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1346]
(Plus une réflexion) 
Je pense que c'est top d'avoir enlevé les pages intermédiaires, mais ce serait cool dans le parcours et la pédagogie de signaler qu'on change de thematique
Je pense que les nouvelles maquettes proposées par @jeremiecook regleront clairemetn le gros du probleme, mais en attendant avez vous une idée de ce qu'on pourrait faire pour signaler ce changement "'en douceur" sans avoir à passer une page @bjlaa @florianpanchout ?

**Comment by bjlaa** [comment]
Est-ce qu'on ne pourrait pas changer la couleur de fond de la top bar indiquant le résultat du test (au dessus du formulaire) en fonction de la catégorie + ajout d'un titre "Nom de la catégorie" au dessus du titre de la question dans le formulaire ?

**Comment by jeannelf** [comment]
si cest pas trop long et que ca rend bien why not ji'magine pas trop
mais en vrai cest pas le plus prio des retours sinon

**Comment by jeremiecook** [comment]
Pourquoi elles ont disparu les pages intermédiaires ?

**Comment by florianpanchout** [comment]
Si on change la couleur de la top bar les gens vont penser que le total est lié à la catégorie

**Comment by jeannelf** [comment]
> Pourquoi elles ont disparu les pages intermédiaires ?

c'est un gros lieu de drop actuellement, donc cest l'occasion de tester

**Comment by florianpanchout** [comment]
[Proposition rapide ici](https://nosgestesclimat-git-1346-nos-gestes-climat.vercel.app/)

**Comment by jeannelf** [comment]
ah trop bien je valide grave
il manque juste la bande sur la question repas 
<img width="1064" alt="Capture d’écran 2023-10-02 à 11 45 23" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/89336b0c-1d6c-46e8-9b56-be5462dee75b">

**Comment by bjlaa** [comment]
Très cool !

**Comment by Clemog** [comment]
> Proposition rapide ici

J'allais le proposer ahah, on avait pensé à ça il y a qques temps, chaud de tester !
