### ISSUE TITLE
Refonte / Design / Rajouter des animations // moins statique ?

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1347]
En général moins d'animations qu'en prod
- Les animations hover sur les boutons ont disparu
- 🔴 Manque des transitions / animations css pour l'ouverture des cartes, les cliques (ex: points infos, graphe des sous postes en bas des questions, coche des mosaïques, affichage des notifications) → pour moi c'est vraiment un point bloquant car on perd beaucoup en fluidité    
- Sur l'écran action, je me permets de remettre ici l'absence d'animations de transition qui est assez perturbant

**Comment by jeannelf** [comment]
c'est trop cool plein de hover hihi merci
juste il n'y en a pas sur les réponses aux questions (alors qu'il y en a sur les sugg et plein d'autres boutons) : c'est long d'ajouter un hover en plus sur ce composant ? 🙏 
<img width="655" alt="Capture d’écran 2023-10-04 à 09 16 10" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/c065a1bf-fbf6-4372-85d9-e64042e48945">

**Comment by florianpanchout** [comment]
Done

**Comment by jeannelf** [comment]
cest mergé ? je vois ps encore sur pre
