### ISSUE TITLE
Refonte / Design / Variations sur le total - rallonger le temps

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1349]
Le changement dans le total saute beaucoup mieux aux yeux en v1, car
- il est "animé" et pas statique
- il reste 2 sec au lieu d'une
https://www.loom.com/share/18f50f7fc8e14ffea405345a76e3af2d

Peut on faire la meme chose en v2? 

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/e60c1cc0-4681-46e2-8cb5-d9bffe52b8c2)

**Comment by florianpanchout** [comment]
[Wesh](https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1343)
