### ISSUE TITLE
Refonte / Page groupes : changer de nom ?

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1353]
Aujourd'hui cette page s'appelle groupes mais on en parle comme "challenge tes amis" donc ce serait super de renommer et d'harmoniser 

- menu 🟠 => "Amis"

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/ff7da583-10ac-47be-9076-72610841d69f)

- nom de la page 🟢  => on laisse "Groupes d'amis"
- titre de l'onglet 🟠 => "Amis"

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/f3659c07-788a-4192-851d-4e079c22ec07)

- url 🟤 => ce serait bien de mettre /amis, et de rediriger /groupes vers /amis
mais peu prioritaire au pire

légende : 🟢  on laisse tel quel 🟠  on change 🟤 je sais pas ?

**Comment by bjlaa** [comment]
Hmm, je suis plutôt d'avis de laisser l'intitulé "groupe" qui me parait plus inclusif que "amis" ; typiquement si tu le fais avec ta famille ou tes grand-parents, ça ne correspond pas vraiment. Je vois mal l'intérêt de réduire le scope des groupes de personnes à cibler ici 😕

**Comment by jeannelf** [comment]
Sur fb tu es bien ami avec ta fratrie non? ;p c'est plus dans l'optique réseaux sociaux de "amis" et pour appliquer les designs que @jeremiecook avait fait à la base pour groupes mais cest comme vous préférez

**Comment by bjlaa** [comment]
Alright. On remplace donc "Groupes" par "Ami·e·s" pour trigger les reac' de droite ?

**Comment by jeremiecook** [comment]
Les points médians ne sont pas recommandés, notamment pour des raisons d'accessibilité... 

En langage épicène, ChatGPT me propose "Contact", "Proches", "Réseau", "Communauté", "Tribu" mais je les trouve tous moins clairs qu' "Amis"

Du coup je sais pas bien quelle est la meilleure solution. @jeannelf ?

**Comment by bjlaa** [comment]
Après réflexion, je suis pour "Amis", notre objectif n'est pas de faire du militantisme orthographique mais de toucher un maximum de monde sans braquer si possible sur ce genre de détails.

**Comment by bjlaa** [comment]
Vous pouvez me traiter de vendu  :smiling_face_with_tear:

**Comment by jeremiecook** [comment]
J'étais en train de me dire la même chose... Choisissons nos batailles ^^

**Comment by JuliePouliquen** [comment]
Ça me va aussi après lecture de votre débat :smile:
