### ISSUE TITLE
Refonte / Lorsqu'on charge une nouvelle page le bandeau de localisation s'affiche puis disparait

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1357]

**Comment by jeannelf** [comment]
(gif pour mieux comprenre le pb dans [notion](https://www.notion.so/accelerateur-transition-ecologique-ademe/Sept-23-Recettage-refonte-6a2dd05211e14c0fb78e32f1b4abc520?pvs=4#8a8585c400dd468fbd601b85c2390265))

Ca se passait sur quelle page ? je la retrouve pas @Clemog

**Comment by Clemog** [comment]
C'ets fix non ?

**Comment by jeannelf** [comment]
si tu le dis ! je sais pas ou le tester mais parfait du coup :)
