### ISSUE TITLE
Refonte / Le md n'est pas correctement affiché pour les “infos” (blockquotes)

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1359]

**Comment by jeannelf** [comment]
@florianpanchout en fait cest toutes les parties un peu "callout" des infos qui s'affichent mal en effet

**Comment by jeannelf** [comment]
Sorry je vois quelques petits soucis : 
- la couleur ne contraste pas trop, il faudrait soit une version plus claire de la couleur de fond soit un gris plus net
- le padding vertical est inégal (petit en haut grand en bas) => à uniformiser

<img width="903" alt="Capture d’écran 2023-10-03 à 10 45 30" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/2e2d063b-9f5e-4e87-839c-fcb8a862ebc8">
