### ISSUE TITLE
Refonte / Manque une majuscule aux suggestions

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1360]

**Comment by jeannelf** [comment]
Majuscule à TOUS les mots c'est peut etre un peu bcp non @florianpanchout ? 😂 
Pourquoi pas carrément JE SUIS SEUL tant qu'on y est ??

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/ce07aa83-ac04-42d1-b662-b294ddd80198)


Enfin si cest possible quoi mettre juste la premiere lettre de la phrase en MAJ

**Comment by florianpanchout** [comment]
Je Fais Ce Que Je Veux
