### ISSUE TITLE
Refonte / Gestion des unités à revoir ?

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1363]
Les unités affichées devraient être affichées comme sur le site actuel et non depuis le modèle : pour le français, ça implique des (s) par endroits (ex: an(s)). pour l'anglais, les unités ne sont pas traduites actuellement 

@Clemog a plus d'infos que moi hésitez pas à voir avec lui si questions 😅  @bjlaa @florianpanchout

**Comment by jeannelf** [comment]
En prod, c'est simplement un dictionnaire qui permet de gérer l'affichage fr mais aussi en-us https://github.com/incubateur-ademe/nosgestesclimat-site/blob/master/source/locales/units.yaml

**Comment by Clemog** [comment]
> En prod, c'est simplement un dictionnaire qui permet de gérer l'affichage fr mais aussi en-us https://github.com/incubateur-ademe/nosgestesclimat-site/blob/master/source/locales/units.yaml

Yes clairement pas optimal..

Pour les trad, on a peut etre pas le choix

Mais pour les pluriels, on devrait peut etre le gérer dynamiquement (dans un second temps ?) ou dans un dictionnaire séparé
