### ISSUE TITLE
Refonte / La liste des questions dans le profil semble un peu moins fine qu'actuellement

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1364]

**Comment by bjlaa** [comment]
Possible de préciser ce qui est attendu ici ? J'ai noté un problème d'affichage au niveau du chiffre affichant le nombre de sous-questions, ex : 


![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/12382534/011214ee-fd37-4842-9107-ca42af0e5b97)

Sinon je n'arrive pas à reproduire ton affichage @Clemog :


![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/12382534/0d46462a-a08f-4673-b2ad-67205497ae5d)

est-ce que tu utilises un navigateur en particulier ?

**Comment by bjlaa** [comment]
Oui okay, problème de style sur Safari, je corrige ça ✔

**Comment by Clemog** [comment]
Je n'ai pas bien compris la question @bjlaa ?
Je mentionnais le fait qu'on ne retrouvais pas l'affichage de la prod actuelle :

<img width="971" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/55186402/6956d53e-62a8-4b89-bd27-42b3e875e38f">

**Comment by Clemog** [comment]
yes c'était sur safari mon test de la refonte :)

**Comment by Clemog** [comment]
Autre point qui rejoint un sujet du notion : dans le profil on ne devrait afficher que les questions auxquelles l'utilisateur à répondu (comme c'est le cas actuellement en prod)

**Comment by jeannelf** [comment]
j'ai l'impression que cest bon now, mais @Clemog peux tu recetter pour voir si ca correspond bien auc omportement que tu attendais ?

**Comment by Clemog** [comment]
Pour l'affichage, carrément :)

Sur le fait que le profil contienne seulement les questions répondues, pas encore je crois :)
