### ISSUE TITLE
Refonte / Bug 🪲 Challenge des amis absent "oups"

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1370]
![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/b85562c8-94d4-4391-b739-2b72ed285039)

**Comment by jeannelf** [comment]
Le parcours Amis a un comportement étrange un peu buggé,
Dans cette vidéo on voit meme qu'il peut avoir 2 comportements : 

Comportement 1
- je crée un groupe
- ca me renvoie direct vers le test
- je fais le test
- j'ai mon résultat ✅ 
- quadn je vais sur Amis => Application error ❌ 

Comportement 2
- je crée un groupe
- ca me renvoie direct vers le test
- je fais le test
- avant le résultat => Application error ❌ 

Quel est le comportement normal?
En prod en tout cas c'est
- je créeu n groupe
- je suis sur la page du groupe
- on ne m'inicite pas à faire le test => donc le fait d'amener vers le test en V2 c'est cool mais ca marche pas



https://www.loom.com/share/915b7b187be1414cad7c46fb75c71c58?focus_title=1&muted=1&from_recorder=1

**Comment by bjlaa** [comment]
Le comportement souhaité est : 
1) J'ai déjà fait mon test :
- je crée mon groupe
- je suis redirigé vers la page de résultats du groupe
2) Je n'ai pas encore passé mon test :
- je crée mon groupe
- je suis redirigé vers le test
- une fois mon test terminé je suis redirigé vers la page de résultats du groupe
Pas idéal mais on améliorera ça.

Il y a un binz quelque part je regarde ça

**Comment by jeannelf** [comment]
Toujours ça apres avoir fait le test (nav privée pour avoir un cas ou j'ai "jamais fait le test") 

<img width="1058" alt="Capture d’écran 2023-10-04 à 18 24 55" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/0705aa1c-254e-4673-8a1c-9d1f52742957">

**Comment by bjlaa** [comment]
je viens de lancer le merge il y 2 minutes 🙈 tu peux retester dans 3 4 minutes ou bien domani !

**Comment by jeannelf** [comment]
mdr pardon trop oppressante lameuf, oui bien sur 😂

**Comment by bjlaa** [comment]
grave c'est relou Jeannette

**Comment by jeannelf** [comment]
attention... i'm gonna cry.....

**Comment by jeannelf** [comment]
allez je check ca demain ciao tout le monde

**Comment by bjlaa** [comment]
Une réf au standup-gate gravée à tout jamais dans Github, j'adore !! 😍

**Comment by jeannelf** [comment]
et ca marche !

**Comment by jeannelf** [comment]
cf discussion ci dessus, je suis désolée j'ai du mal faire la recette qq part...

## Parcours souhaité
    - je n’ai pas fait le test ⇒ je crée le groupe ⇒ on me renvoie au test ⇒ je finis le test ⇒ page groupe
    - j’ai déjà fait le test ⇒ je crée le groupe ⇒ je reste sur la page groupe qui grab direct mon résultat
  
## Parcours actuel
    - ✅ je n’ai pas fait le test ⇒ je crée le groupe ⇒ on me renvoie au test ⇒ je finis le test ⇒ page groupe
    - ❌ j’ai déjà fait le test ⇒ je suis renvoyé au test et donc à la page “voir mon résultat” qui n’est plus supposée exister



![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/c5e7d446-1da8-4763-997d-47c45017d6a7)

**Comment by bjlaa** [comment]
What @florianpanchout comment c'est possible que cet état soit encore affiché 😄

**Comment by florianpanchout** [comment]
C'est l'écran qui s'affiche lorsque l'on retourne sur le test alors qu'il est complété. Ça me fait aussi mal qu'à vous

**Comment by jeannelf** [comment]
Je ne peux pas tester à cause de #1420
