### ISSUE TITLE
Refonte / Tuto / Remonter le bouton "c'est parti"

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1375]
Aujourd'hui le "c'est parti" est aapres les 3 questions pour creuser
Mais selon la taille des écrans ca passe pas 

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/7b2a8ec6-5c64-4be6-a0a6-5f3ad3abeae1)

Du coup ma reco c'est : 

- remonter le bouton sous la boite
- faire attention à aligner le CTA avec la fin du cadre
- laisser le reste tel quel

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/9fe4b7f1-1938-46d6-83b6-01f6a743d4ba)

**Comment by florianpanchout** [comment]
J'ai aussi supprimé le titre sur mobile : c'est plus raccord avec le test (ou le titre est aussi caché sur mobile) et sinon on ne voit pas les boutons. Pas sur de mon coup donc dites moi si je remets.

(par contre on va avoir du mal à mesurer l'effet sur le drop vu que ça arrive en même temps que la suppression du loader)

**Comment by jeannelf** [comment]
pas grave pour la mesure on mettra ca sur le compte de l'amélioration en général ahah

**Comment by florianpanchout** [comment]
Oh c'est quand même important de savoir ce qui est rédhibitoire et ce qui ne l'est pas pour nos utilisateurs (et je parie 10€ sur le fait que tous les gens qui actuellement cliquent sur "Faire le test" auront la patience de trouver le bouton "C'est parti !") (ce qui ne veut pas dire qu'il faut cacher le bouton pour autant)
