### ISSUE TITLE
Refonte / Affichage des règles "non applicables"

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1377]
Les règles non applicables sont très difficilement visibles 

<img width="767" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/55186402/4f74827d-83d7-45cc-b62b-447eba0570b8">

ping @jeannelf @florianpanchout 

Je remarque s'ailleurs un souci dans les unités, lié à publicodes-commun, je regarde

**Comment by jeannelf** [comment]
ah oui ahaha en effet sympa le blanc sur blanc 
On peut mettre ca en grisé plutôt @florianpanchout ?

(et fyi j'ai regardé cette page est assez utilisée, "seulement" 1% des visites en 2023 mais quand meme 210K visualisations de la page https://preprod.nosgestesclimat.fr/documentation/bilan)
<img width="1020" alt="Capture d’écran 2023-10-05 à 10 19 21" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/003e56fe-7485-4ca0-b5ce-fe24b4ffe267">

**Comment by Clemog** [comment]
Je pense que je suis à 219000 visualisations en perso ahah

**Comment by Clemog** [comment]
Actuellement : 
<img width="795" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/55186402/3e4e1841-b75c-4963-9f43-b8102f1a1a7f">

**Comment by jeannelf** [comment]
aah super le nouveau toggle !

**Comment by Clemog** [comment]
De mon côté, pas du tout convaincu : c'est important d'afficher tous les éléments des sommes ? C'est une doc plutôt "expert/curieux", c'est important de tout afficher
+ pour le dev du modèle c'est important d'avoir tout à l'écran, quand on visualise la doc, c'est bien de voir directement ce qui est applicable ou non

**Comment by florianpanchout** [comment]
Alors j'ai rien fait hein. C'est le package publicodes-react qui a évolué

**Comment by Clemog** [comment]
Ohh trop dommage
