### ISSUE TITLE
Refonte / Intégrer le logique des règles optimisées

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1379]
Il y a quelques mois maintenant, un gros travail d'@EmileRolley a permis de réduire drastiquement le poids du modèle chargé via une version optimisée permettant d'établir une première version du calcul. Plus d'info ici : https://incubateur-ademe.github.io/publicodes-tools/modules/optims.html.

Aujourd'hui, dans la refonte, on charge uniquement ce modèl optimisé qui permet de faire le calcul mais ne permet pas d'avoir accès à l'ensemble des règles. De mémoire (mais je ne retrouve pas le cas) certaines questions peuvent ne pas apparaître via cette version en l'absence de règle.

Ex: Par défaut, la piscine est à `non`, donc les enfants de piscine ne sont pas dans le modèl optimisé, si je répond `oui` à la piscine, ça casse. (actuellement non, du coup bizarre @EmileRolley ?)

Une première solution *simple* mais très dommageable pour la feature serait de charger directement le modèle complet directement ([ici](https://github.com/incubateur-ademe/nosgestesclimat-site-nextjs/blob/413efac13901d7c486e5ad88fd01da1af550f1dc/src/hooks/useRules.ts)) plutôt que l'`-opti`.

Question pour @florianpanchout et @bjlaa : le fait d'utiliser Next permet-il de pré charger le modèle côté serveur et donc de ne pas avoir d'enjeu à ce niveau là ?

En vu de la réintégration de l'optim, il faut avoir en tête:

- Dans la doc, le modèle complet doit toujours être chargé
- Certains questions déclenchent le chargement du modèle complet selon [la logique ici](https://github.com/incubateur-ademe/nosgestesclimat-site/blob/f09023289aa1ee810e3e5b27ac94fe4b5de08017/source/RulesProvider.tsx#L175) `
- Les warnings sur les unités doivent être [ignorés pour l'optim](https://github.com/incubateur-ademe/nosgestesclimat-site/blob/f09023289aa1ee810e3e5b27ac94fe4b5de08017/source/RulesProvider.tsx#L103)

(ping @jeannelf)

**Comment by EmileRolley** [comment]
> Ex: Par défaut, la piscine est à `non`, donc les enfants de piscine ne sont pas dans le modèl optimisé, si je répond `oui` à la piscine, ça casse. (actuellement non, du coup bizarre @EmileRolley ?)

C'est un bug ça, l'optimisation ne prend pas en compte l'applicabilité conditionnelle des règles pour l'instant.

Ce qui est étrange c'est que ça devrait casser également sur la version en prod actuellement non ? C'est le même modèle optimisé qui est chargé sur la version next et en prod non ?

**Comment by Clemog** [comment]
> C'est un bug ça, l'optimisation ne prend pas en compte l'applicabilité conditionnelle des règles pour l'instant.

Non aujourd'hui ça ne casse pas :)
Mais je me dis que ça "devrait" car on n'a pas besoin des règles enfants de la piscine au départ typiquement

**Comment by Clemog** [comment]
Mais du coup t'as rep à la question ! ;)

**Comment by florianpanchout** [comment]
Quel serait le poids du modèle si on y ajoutait le contenu des questions qui ont besoin de la version non optimisée ? Parce que j'ai l'impression que c'est un mécanisme qui n'est pas trivial (et qui peut, entre autres, poser problème pour le offline). Donc si c'est pour gagner moins de 20k j'aurais tendance à intégrer tout ce dont on a besoin directement dans l'optim.

Je corrige tes points 1 et 3 en attendant

**Comment by jeannelf** [comment]
je ne sais pas quoi regarder n'hésitez pas à me dire si faut check un truc précis sinon je vous fais confiance

**Comment by Clemog** [comment]
De mon côté j'ai toujours l'optim dans la doc je crois ?

**Comment by EmileRolley** [comment]
Je confirme, la page de doc pour la règle `services . sociétaux` n'est pas accessible par exemple : https://preprod.nosgestesclimat.fr/documentation/services-soci%C3%A9taux
