### ISSUE TITLE
Refonte / ajouter la traduction des articles de blogs

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#1384]
Les articles accessible sur `/blog` ne sont actuellement disponible quand français. Il faudrait donc les traduire en anglais.

Contrairement aux autres pages du site, je ne pas qu'ajouter de nouveaux scripts de traductions soit nécessaire et souhaitable. En effet, on veut s'assurer de la bonne qualité des traductions et elles devraient être faites à la main par une personne maîtrisant l'anglais.

Qu'est-ce que vous en pensez @jeannelf et @JuliePouliquen ?

**Comment by florianpanchout** [comment]
Juste pour être sur : actuellement les articles ne sont bien disponibles qu'en français ?

**Comment by JuliePouliquen** [comment]
Hello @EmileRolley j'avais plutôt gardé en tête justement que nous ne souhaitions pas traduire le blog. Exactement parce que nous n'avons pas de bilingues dans l'équipe et que ça nécessite du vrai travail de traduction. 
À ce stade, est-ce pénalisant d'avoir une version anglophone du site qui ne dispose pas du blog ?

**Comment by jeannelf** [comment]
pour moi ca n'est pas genant
