### ISSUE TITLE
Refonte / Mode sondage - clic sur logo => ramener à la home

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1389]
Il faudrait pouvoir revenir facilement à NGC classique depuis sondaage
Peut on faire en sorte que quand on clique sur le logo ca renvoie à NGC.fr?

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/81af3dc2-6f3d-457e-81b7-d61413561af4)

**Comment by bjlaa** [comment]
Corrigé directement sur la branche `sondages` (pas de PR)

**Comment by jeannelf** [comment]
sorry @bjlaa juste un petit truc : ca renvoie vers le site racine mais en anglais, je ne saias pas pourquoi ?
https://www.loom.com/share/dbf670a48c614da79f86d4b5b018c78e?focus_title=1&muted=1&from_recorder=1

**Comment by bjlaa** [comment]
et quand tu ouvres le site actuel est-ce que tu l'as aussi en anglais ou bien c'est uniquement quand tu cliques sur ce lien précis ?

**Comment by jeannelf** [comment]
ahhh oui en effet j'avais du faire un test sur l'anglais pour le blog, okkk désolée fausse alerte 😅
