### ISSUE TITLE
Refonte / le tutoriel n'est pas affiché lorsque que l'on arrive via l'URL d'une question

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#1391]
Lorsque l'on arrive sur le site pour la première fois avec une URL de la forme : https://preprod.nosgestesclimat.fr/en/simulateur/bilan?question=transport.ferry.présent, on devrait être redirigé vers le tutoriel.

**Comment by jeannelf** [comment]
alors du copu avec le nouveau fonctionnement @florianpanchout on est redirigés vers le tuto puis la premiere question direct, pas une question en cours
J'ai l'impression que c'est le bon fonctionnement côté user / produit mais juste c'est nouveau right ?

**Comment by florianpanchout** [comment]
C'est à dire "la première question" ?

Normalement on a le même fonctionnement qu'en prod : la question dans l'url n'est pas prise en compte sauf si l'on a déjà répondu à toutes les questions précédentes
