### ISSUE TITLE
Refonte / Bug 🪲 Page doc / modele fait une 404

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1393]
https://preprod.nosgestesclimat.fr/modele

 =

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/00e9e38f-111c-45c4-8a9d-73badced4a84)

**Comment by florianpanchout** [comment]
Bah https://nosgestesclimat.fr/modele

**Comment by bjlaa** [comment]
C'est sensé être quewa cette page de doc ?

**Comment by jeannelf** [comment]
mdr des baarres en effet @florianpanchout 

@bjlaa cest quand on clique sur [💡 En savoir plus sur notre modèle](https://nosgestesclimat.fr/mod%C3%A8le) dans la doc, mais du coup on s'en fout ahha 
<img width="524" alt="Capture d’écran 2023-10-09 à 12 25 05" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/5d95abdf-3f7f-4d1e-8789-87d794f77768">

**Comment by bjlaa** [comment]
Ah ! La c'est différent 😄 je corrige
