### ISSUE TITLE
Refonte / Bug 🪲 Notifications importantes qui ne s'affichent pas

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1394]
cf échange ici https://www.notion.so/accelerateur-transition-ecologique-ademe/Sept-23-Recettage-refonte-6a2dd05211e14c0fb78e32f1b4abc520?pvs=4#d4721cdb327b4891bf016beea621b220

**Comment by florianpanchout** [comment]
La notification sur le nombre de voyageurs [semble avoir disparue sur la version preprod](https://github.com/incubateur-ademe/nosgestesclimat/blob/preprod/data/transport/transport%20.%20voiture.publicodes) ?

**Comment by florianpanchout** [comment]
(@Clemog @JuliePouliquen)

**Comment by Clemog** [comment]
Ah oui étrange !

**Comment by Clemog** [comment]
C'est corrigé, sorry !
https://github.com/incubateur-ademe/nosgestesclimat/commit/7418874975655ebcbe03e1736a76dc2dd59c7ac8
