### ISSUE TITLE
Refonte / Bug 🐞 : rétablir le comportement de focus au passage à la question suivante

### ISSUE THREAD

**Issue by bjlaa** [incubateur-ademe/nosgestesclimat-site#1397]
- [x] passer une question
- [x] le focus doit se placer sur l'intitulé de la question
- [ ] ajouter un attribut `aria-live="polite"` > à faire plus tard

**Comment by florianpanchout** [comment]
Quel est le but de cette issue ? Parce que ça casse la navigation via enter (qui n'est pas un "vrai" besoin utilisateur ceci dit, donc pas prioritaire)

**Comment by bjlaa** [comment]
ça vaut peut-être le coup de réfléchir à l'intégration d'une touche magique pour passer : peut-être plus discret que "Echap", par exemple "Ctrl + shift + N"

**Comment by florianpanchout** [comment]
Konami code pour chaque changement de question

**Comment by bjlaa** [comment]
⬇ + ➡ + A
