### ISSUE TITLE
Refonte / Bug 🐛  : la page profil fait planter l'intégration iframe standalone

### ISSUE THREAD

**Issue by bjlaa** [incubateur-ademe/nosgestesclimat-site#1398]

**Comment by jeannelf** [comment]
@bjlaa tu peux me renvoyer les liens pour tester les iframe stp ? je les trouve plus 🙈

**Comment by bjlaa** [comment]
avec joie ! https://preprod.nosgestesclimat.fr/demo-iframe et https://preprod.nosgestesclimat.fr/demo-iframeSimulation
