### ISSUE TITLE
Refonte / Warnings Publicodes pendant le test

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1401]
Beaucoup d'erreurs sont remontées dans le console pendant le test 

> On essaie d'ajouter la catégorie "logement" à un dottedName qui contient déjà la catégorie "transport"

cf : https://mattermost.incubateur.net/betagouv/pl/pe5xofcpxpdhtdknpi18k3m61c

**Comment by florianpanchout** [comment]
Nope. Tu peux regarder dans la console et voir si tu as du rouge qui s'affiche

**Comment by jeannelf** [comment]
la console sentry?

**Comment by florianpanchout** [comment]
Nope, la console de ton navigateur

**Comment by jeannelf** [comment]
ah gné mdr ok

**Comment by jeannelf** [comment]
<img width="1369" alt="Capture d’écran 2023-10-11 à 12 17 14" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/9ece4f2b-9293-41dd-98d8-506ab2413092">

Je vois trois types de soucis qui ressortent pendant le test je comprends pas grand chose mais ca ne m'a pas l'air bloquant right @florianpanchout ?

- Duplicate form field id in the same form
Multiple form field elements in the same form have the same id attribute value. This might prevent the browser from correctly autofilling the form.
To fix this issue, use unique id attribute values for each form field.

- Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute refers to a form field by its name, not its id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, refer to form fields by their id attribute.

- Incorrect use of <label for=FORM_ELEMENT>
The label's for attribute doesn't match any element id. This might prevent the browser from correctly autofilling the form and accessibility tools from working correctly.
To fix this issue, make sure the label's for attribute references the correct id of a form field.

**Comment by florianpanchout** [comment]
Oh ça c'est juste Benouille qui fait de l'accessibilité
