### ISSUE TITLE
Rajouter la possibilité de passer les questions avec la touche Esc

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1403]
Suite à https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1397

**Comment by bjlaa** [comment]
🚓 👮 Attention, la touche "Esc" est utilisée par les utilisateurs en situation de handicap. Privilégier une autre touche ou combinaison de touches

**Comment by jeannelf** [comment]
tu peux me redire la combinaison de touches stp @bjlaa ?

**Comment by bjlaa** [comment]
Ctrl + Shift + Esc 🧙 ✨
