### ISSUE TITLE
Refonte / bug redirection /tutoriel

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#1405]
Avec une nouvelle session, lorsque l'on essaie d'accéder à toutes autres pages que la home, on est redirigé vers la page tutoriel.

**Comment by jeannelf** [comment]
@florianpanchout désolée le fix a dû casser qqch,
car maintenant si on m'envoie l'URL d'une question ([exemple](https://nosgestesclimat.vercel.app/simulateur/bilan?question=transport.voiture.utilisateur_r%C3%A9gulier)) , je suis bien redirigé vers le tuto, mais apres ca charge indéfiniment : 

https://www.loom.com/share/4aa8fd3d51d440759c409c96f1554ae6 

Ah et tiens d'ailleurs ca le fait aussi pour les autres pages comme la page [actions](https://nosgestesclimat.vercel.app/actions) alors que ca n'est paas le comportement souhaité si je ne m'abuse  : tuto puis simulateur/bilan qui charge indéf

**Comment by florianpanchout** [comment]
Yes c'est corrigé en preprod (oui c'est compliqué à suivre)

**Comment by jeannelf** [comment]
Alorss....

Comportement actuel

- P1 est en train de faire le test
- P1 partage le lien d'une question en cours
- P2 ouvre le lien 
- ❌ ca montre vite fait la premiere question => possible d'éviter cette étape ?  
- ✅  puis ca envoie au tuto

https://www.loom.com/share/d32b861a30a7427e8c8e3adf4e7d97b2


Par contre pour le partage des autres pages (actions, doc..) cest bon on a le comportement souhaité : renvoie vers la page dite et si on va sur le quiz on redémarre au tuto ✅

**Comment by florianpanchout** [comment]
Sacrés P1 et P2

**Comment by jeannelf** [comment]
cest a tester sur vercel ou preprod ?

**Comment by florianpanchout** [comment]
Tous les derniers correctifs sont sur preprod

**Comment by jeannelf** [comment]
ok alors ca fonctionne pas j'ai le meme probleme

**Comment by florianpanchout** [comment]
My bad, c'est corrigé (problème de build de la preprod)
