### ISSUE TITLE
Refonte / Récupérer le(s) dernier(s) article(s) de blog

### ISSUE THREAD

**Issue by florianpanchout** [incubateur-ademe/nosgestesclimat-site#1406]

**Comment by bjlaa** [comment]
À faire demain, après la sortie de l'article de Julie.

**Comment by jeannelf** [comment]
@bjlaa il est noté comme étant de août 2023, c'est possible de changer pour octobre ?
je sais pa si ca se fait de ton côté ou chez @JuliePouliquen 

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/c165debd-a464-4b37-9c7d-ef9886757cd0)

**Comment by jeannelf** [comment]
ya toujours écrit aout chez moi @bjlaa pas toi ?

**Comment by JuliePouliquen** [comment]
> @bjlaa il est noté comme étant de août 2023, c'est possible de changer pour octobre ? je sais pa si ca se fait de ton côté ou chez @JuliePouliquen

À ce stade, je n'ai pas moyen d'indiquer des metadata pour les articles de blog. On avait listé des trucs à ajouter dans une V2 ici : #1137

**Comment by bjlaa** [comment]
Oups ! C'est un oubli de ma part, j'ai corrigé des deux côtés
