### ISSUE TITLE
Refonte / 🪲 Bug modele ou site? Question logement chauffage chelouuuue

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1414]
https://nosgestesclimat.vercel.app/simulateur/bilan?question=logement.chauffage

![Image](https://github.com/incubateur-ademe/nosgestesclimat-site/assets/144152881/1338dc1c-d8ac-4506-857d-0114ae6a3575)

**Comment by Clemog** [comment]
La logique de définition des enfants des mosaïques ne semble pas avoir été reprise entièrement. Normalement, on passe une clé lors de la définition de la mosaïque pour indiquer quels enfants doivent faire partie de la mosaïque 
J'ai l'impression que tout se passe dans `everyMosaicChildWhoIsReallyInMosaic`, qui renvoie des règles qui ne devraient pas être dedans, par exemple `logement . chauffage collectif` ou `logement . chauffage . biogaz . part`

**Comment by Clemog** [comment]
Faut qu'on mettre en avant le wiki 🤓 https://github.com/incubateur-ademe/nosgestesclimat-site/wiki/mosaic
