### ISSUE TITLE
Refonte / Ajouter des trackers Matomo

### ISSUE THREAD

**Issue by jeannelf** [incubateur-ademe/nosgestesclimat-site#1416]
- Clic sur la liste des questions
- clic sur les catégories

**Comment by florianpanchout** [comment]
Je [les vois bien ici](https://matomo-incubateur-ademe.osc-fr1.scalingo.io/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?period=day&date=2023-10-11&idSite=1&category=General_Actions&subcategory=Events_Events) (catégories "questions-list" et "formulaire"). Tu as peut être testé avant que la preprod soit mise à jour (voir https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1405#issuecomment-1757449104)

**Comment by jeannelf** [comment]
oui super ils sont apparus entre temps ! ca met du coup au moins 3h a arriver pcq j'avais tester ce matin

**Comment by bjlaa** [comment]
Okay top !
