### ISSUE TITLE
Refonte / petits fix documentation

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#1417]
- [ ] Ajouter un bouton de retour au test dans la doc
- [ ] J'ai l'impression qu'on a un mini souci de scroll (cf différence entre l'actuel et la refonte)
- [ ] Alignement des textes sur mobile 
<img width="372" alt="image" src="https://github.com/incubateur-ademe/nosgestesclimat-site/assets/55186402/e4db669e-53d8-47f6-a271-a72e636c6850">

**Comment by jeannelf** [comment]
je close car je mets ca sur notion :)
