### ISSUE TITLE
Retrouver et mettre à jour une simulation antérieure

### ISSUE THREAD

**Issue by TanguyMordellet** [incubateur-ademe/nosgestesclimat-site#1441]
Bonjour, est-il possible de récupérer une ancienne simulation afin de la mettre à jour ? Je n'ai pas vu ce sujet traité dans la FAQ. Merci.

**Comment by JuliePouliquen** [comment]
Bonjour @TanguyMordellet
Vos données ne sont stockées que dans votre navigateur. Tant que vous n'avez pas effacé votre historique, vous pouvez retrouver vos simulations sur la page /profil. De là, vous pouvez également visionner vos réponses précédentes et les modifier.
Depuis peu, nous laissons la possibilité aux utilisateurs de renseigner leur mail en fin de parcours pour réaccéder à ses données ultérieurement. Auquel cas, le lien présent dans le mail vous renvoie systématiquement à cette précédente simulation.
