### ISSUE TITLE
Mieux ranger les fichiers

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#165]
On hérite de l'architecture des dossiers de mon-entreprise, qui mérite d'être grandement simplifiée, remise à plat.

Plutôt facile à corriger... mais surtout si plus aucune PR en attente.

**Comment by laem** [comment]
En particulier, source/sites/publicodes

**Comment by mquandalle** [comment]
On a aussi simplifié l’arborescence sur mon-entreprise https://github.com/betagouv/mon-entreprise/tree/master/mon-entreprise/source

Normalement le "langage server" de TypeScript s'occupe de ré-écrire tous les chemins lorsqu'on bouge un répertoire

**Comment by laem** [comment]
Excellent, il faut que je teste ça, merci :) 
Il gère même le reste de fichiers .js ou d'imports non typés ?

**Comment by mquandalle** [comment]
Il me semble que oui, mais peut-être que ça dépend de l'option `allowJs: true` du `tsconfig.json`.
