### ISSUE TITLE
Mettre en valeur la suggestion "par mois" quand la réponse est "par an"

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#181]
On peut mettre du *markdown* dans le yaml et l'intérprêter dans InputSuggestion.tsx.

**Comment by Clemog** [comment]
Je ne suis pas sur de comprendre le cas d'usage ?

**Comment by laem** [comment]
Quand l'input se fait en x par an, mais qu'une des suggestions dit "y par mois", il s'agirait de mettre l'accent sur le fait que c'est un type de période différent :)
