### ISSUE TITLE
Partir de zéro au lieu de valeurs moyennes

### ISSUE THREAD

**Issue by Benjamin-Boisserie-ABC** [incubateur-ademe/nosgestesclimat-site#20]
Je trouve bizarre que dès le début les 9t de CO2 (12t quand tout sera implémenté) soient affichées qui plus est avec le message "total provisoire annuel"

De plus, au fur et à mesure de l'évaluation de son empreinte carbone ce total peut diminuer ce qui selon moi peut prêter à confusion. Cela peut induire le type de réflexion "ce mode de vie/comportement fait baisser mon empreinte carbone", réflexion en partie vraie mais qui devrait être "ce mode de vie/comportement contribue à moins augmenter mon empreinte carbone"

--> Je propose donc que le compteur parte de 0t de CO2 pour grossir progressivement au fur et à mesure que l'on répond aux questions

**Comment by laem** [comment]
C'est une bonne remarque, un point de vue différent ! 
Par contre, techniquement c'est plus compliqué. Par exemple, prenons le cas de la voiture, il y a au moins 3 questions : 
- le nb de km
- la motorisation de la voiture 
- l'âge de la voiture
A quel moment déclenche-t-on l'ajout de l'impact de la voiture au bilan total ? 

Dès la 1ère réponse ? Dans ce cas, il faut utiliser de toute façon une valeur moyenne pour les 2 autres questions, donc on aurait une approche hybride qui peut perturber le message. 

Seulement à la complétion de l'ensemble des questions concernant la voiture ? Dans ce cas, l'utilisateur ne verra pas l'influence des kilométrages.

**Comment by jeannelf** [comment]
en discussion pour la nouvelle version du parcours
