### ISSUE TITLE
Section /actions comme un jeu

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#205]
- [x] implémenter un bouton sur les actions "j'achète", l'intégrer dans le calcul
- [ ] mettre en lien avec l'accord de Paris / l'empreinte "écolo" de 2 tonnes voir #113 
- [x] gérer les exclusions : si on sélectionne "pas de viande", on n'affiche plus "diviser la viande par 2"

**Comment by jeannelf** [comment]
cf jeu de carte, en cours !
