### ISSUE TITLE
Récits

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#218]
Dans #176 on introduit des profils types (appelés personas) qui permettent de tester le simulateur pour différents utilisateurs.

On pourrait aller plus loin : 
- permettre de renseigner une situation plus complexe pour la voiture (km = boulot + loisirs + enfants + vacances + famille), pour le logement (surface + DPE)
- pouvoir **commenter** tout ça. "Je vais voir mes parents en voiture à 20km de la ville où j'habite"; "mon logement est chauffé au gaz et je n'ai pas encore envisagé changer cela ou déménager". 
- on aurait alors un **témoignage sûrement plus intéressant que des personas chiffrés sans histoire**, mais la donnée pourrait devenir très sensible : on ne peut imaginer une modération à ce stade, donc pas de publication sur nosgestesclimat.fr

**Comment by laem** [comment]
@JuliePouliquen je suis sur que cette issue t'intéressera

**Comment by JuliePouliquen** [comment]
Hello @laem quel serait le but, pour toi ? Aussi, nous disons-nous que ces personas ont une visée externe, qu'ils font partie de notre communication, des outils proposés ? Ou est-ce "simplement" pour nous, en interne, pour continuellement améliorer le modèle et en voir les impacts sur des parcours-types ?
