### ISSUE TITLE
Faire un widget personnalisé pour les foyers

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#241]
Personnes dans le logement  / personnes dans la voiture.
Tout simplement, afficher l'information dans au-dessus du graphe / dans l'écran "mes réponses".

**Comment by Clemog** [comment]
L'idée est intéressant car afficher ces valeurs permettrait d'insister sur le caractère individuel du calcul en expliquant que l'empreinte des postes qui dépendent de plusieurs personnes sont rapportées à un individu

**Comment by Clemog** [comment]
Lié à #536
