### ISSUE TITLE
Adapter l'affichage des quantités de CO2 (kg, tonnes, gr)

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#26]
![image](https://user-images.githubusercontent.com/1177762/84030145-d100d200-a993-11ea-8a29-a88ef5fb0783.png)

Le code est là : https://github.com/betagouv/ecolab-climat/blob/master/source/sites/publicodes/HumanWeight.js

**Comment by laem** [comment]
Peut-être attendre #6

**Comment by laem** [comment]
Cela peut peut-être se faire via l'API publicodes qui permet de donner un tableau de conversion d'unités en entrée, mais nous aurons peut-être besoin d'améliorer la lib pour obtenir des conversions adaptées (1200 -> 1,2 t; 456 -> 456kg)

**Comment by Clemog** [comment]
Il semble que cette issue est toujours d'actualité : j'avais eu beaucoup de mal à gérer l'affichage des chiffres et des unités lorsqu'il était question de petites valeurs pour le numérique ou bien de valeur importantes comme pour l'empreinte carbone nationale. Et je pense que le travail porte toujours sur la conversion ;)

**Comment by jeannelf** [comment]
géré avec le retravail des unités non @Clemog ?

**Comment by Clemog** [comment]
Pas sur que ce soit avec le travail des unités mais normalement c'est géré depuis un moment côté site, pas côté modèle je crois
