### ISSUE TITLE
Liste d'équipements : bouton bonus joker

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#261]
Dans la liste des équipements numériques, comme dans la future liste de l'électroménager, nous sommes évidemment non exhaustifs. 

On pourrait laisser l'utilisateur cliquer autant de fois qu'il veut sur un bouton joker, point d'interrogation, qui aurait une valeur moyenne.

Par exemple : je remarque que j'ai aussi dans ma cuisine un billig (crépière), une machine nespresso en plus de la machine à café tradi, et un grille-pain => je clique 3 fois sur le bouton joker. 

Idem pour le numérique : j'ai aussi une montre connectée, une enceinte connectée => je clique 2 fois.

**Comment by laem** [comment]
C'est fait pour le textile :) 

À compléter pour les autres.

**Comment by jeannelf** [comment]
https://www.notion.so/accelerateur-transition-ecologique-ademe/ab6b1a539f8845f7abeba10ec8d5af01?v=50bf819f11ca48cbaff909bd2111f338&p=1196523d57d780f2aef8fbaa91a8085f&pm=s
