### ISSUE TITLE
Suivre l'avancement dans la simulation dans l'URL

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#27]
Avec le nom de la question en cours. Avantages : 
- pouvoir utiliser la flèche arrière du navigateur <-- comme expliqué dans #463, pas une bonne idée à mon avis
- le suivi Matomo
- l'indexation SEO

**Comment by Clemog** [comment]
Voir #463 :)

**Comment by bjlaa** [comment]
J'ai l'impression que l'on peut fermer cette issue ?

**Comment by Clemog** [comment]
8 juin 2020 trop dingue ahah
