### ISSUE TITLE
Tenue en charge de /conférence

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#275]
## Tenue côté serveur

- nous utilisons actuelle les serveurs de yjs-webrtc  documentés [ici](https://github.com/yjs/y-webrtc#signaling)
- ce sont des serveurs de signaling, qui ne servent qu'à mettre les internautes en connexion les uns avec les autres
- on pourrait déployer notre propre serveur facilement, au prix de la gestion d'un serveur
- ils disent ça à propos des limites

```
y-webrtc is restricted by the number of peers that the web browser can create. By default, every client is connected to every other client up until the maximum number of conns is reached. The clients will still sync if every client is connected at least indirectly to every other client. Theoretically, y-webrtc allows an unlimited number of users, but at some point it can't be guaranteed anymore that the clients sync any longer**. Because we don't want to be greedy, y-webrtc has a restriction to connect to a maximum of 20 + math.floor(random.rand() * 15) peers. The value has a random factor in order to prevent clients to form clusters, that can't connect to other clients. The value can be adjusted using the maxConn option. I.e.
```

- la seule façon de vraiment savoir la tenue de charge c'est de créer des tests de connexion en navigateur headless (100, 1000)

- nous pouvons à tout moment décider du P2P à une version serveur classique, où chaque utilisateur donne et reçoit les données de simulation du serveur datagir. Voir #231 

## Tenue côté client

L'interface n'est prévue à l'origine que pour quelques connexions. D'après les premiers tests sur le terrain, il semble que ça tienne bien pour des dizaines de personnes (il suffit de scroller pour voir la liste d'utilisateurs). 

C'est assez simple de tester l'interface pour 100 utilisateurs, il suffit de générer des connexions bidons (et au passage, mettre de l'ordre dans le code).

**Comment by Clemog** [comment]
#472

**Comment by jeannelf** [comment]
plus d'actualité avec le mode orga

**Comment by Clemog** [comment]
> plus d'actualité avec le mode orga

Je pense que c'est quand même intéressant de faire un test de charge non ? Y a peut-être moins d'enjeu vu qu'on aura plus le P2P mais si 1000 personnes font leur test en même temps sur le sondage, est ce qu'on est bon ?

**Comment by jeannelf** [comment]
ah oui oui clairement mais les specs techniques sont plus les memes non pcq l'archi a changé?
