### ISSUE TITLE
Bug mode conférence

### ISSUE THREAD

**Issue by fjg** [incubateur-ademe/nosgestesclimat-site#293]
Contexte : 10 participants

Tout fonctionne sur mon écran d'animateur, idem pour les participants (on voit bien 9 personnes). Ils font leur simulation et à la fin plusieurs (pas tous) perdent la connexion : le nbre de connecté tombe à 1, ils ne voient que la moyenne des fr. et plus leur simulation comme s'ils avaient tout perdu. De mon côté tout est ok. C'est arrivé à la fin de la simulation pour les personnes qui ont eu cette expérience.

Capture d'une des personnes qui a eu le bug :

![bug-ngc](https://user-images.githubusercontent.com/91435/122958020-02b3c380-d372-11eb-8839-e4eefda16109.png)

Mon écran :

<img width="850" alt="Capture d’écran 2021-06-21 à 15 47 49" src="https://user-images.githubusercontent.com/91435/122958104-14956680-d372-11eb-823e-c764dcee7805.png">

**Comment by fjg** [comment]
un extrait de la session : https://recordit.co/P2rbfvr0wn

**Comment by laem** [comment]
Mmmh compliqué à débugguer ça. Déjà, on va passer sur notre serveur de signelement. Ça évitera d'avoir à considérer l'hypothèse que c'est le serveur qui est surchargé / redémarré.
