### ISSUE TITLE
Création d'un compte perso

### ISSUE THREAD

**Issue by avenirclimatique** [incubateur-ademe/nosgestesclimat-site#303]
Salut,

Je reçois de plus en plus d'e-mail d'utilisateurs de MicMac (Avenir Climatique) qui avaient un compte. Cet accès connecté permettait notamment de retrouver le résultat des simulations réalisées. Malheureusement il ne fonctionne plus très bien, en tous cas pas la méthode pour retrouver son mot de passe.

Je ne sais pas exactement ce qu'il contenait, mais je suis assez surpris du nombre de personnes qui me contactent pour retrouver leurs accès. J'en conclus que c'était une fonctionnalité que les utilisateurs appréciaient.
Si implémenté dans Nos Gestes Climat, on pourrait également ajouter un module pour suivre nos principaux postes d'émissions mois par mois, comme on peut faire chez Ecolomètre.

Je ne sais pas si c'est prévu, mais en tous cas cela correspond à une demande des utilisateurs, donc je vous en fait part :)

A+

Mathieu

PS: voir aussi : https://github.com/datagir/nosgestesclimat/issues/1060#issue-932684190

**Comment by avenirclimatique** [comment]
Ok, je comprends !

L'avantage c'est que des volontaires pourraient développer ça sans avoir besoin de connaissances poussées en méthodo bilan carbone (il était question d'intégrer des gens de M33 / Sipios au projet à un moment, en pro bono ?)

A+

Mathieu

**Comment by jeannelf** [comment]
en cours de création ;)
