### ISSUE TITLE
Test utilisateur juillet 2021

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#307]
* nan mai 2 tonnes c'est impossible 
    * Clique sur ? en premier dans le bandeau de résultat mauve  dégradé
    * Comprend pas le paragraphe émissions sur le pétrole, raisonnement pas opposition
    * Est paumé dans la liste avec tous les "présents"
    * rajouter un gros bouton "Faire le test"
    * Bêta à enlever dans le `>`
    * **Trouve le bouton c'est parti assez tardivement, le rendre visible via une animation d'accroche**
    * Rajouter "prochaine question" en petit
    * Bouton précédent nécessaire
    * Mettre un bouton mettre à zéro pour les blocs bouffe
    * Distance voiture : bonus, ajouter un calcul d'itinéraire de MIT x N
    * **Mettre la moyenne FR dans le graphe principal**
    * Kiffe la notification voiture
    * Avion a pas lu court trajet, n'arrive pas à revenir en arrière
    * Notification court courrier > 6 alors passez au long courrier question suivante
    * *Modifier* mes réponses, c'est le mot clef qu'il manquait
    * Réponse avion -> mes réponses-> logement, c'est un gros bug de catégories. **Incompréhension**
    * Hausmanien = pierre, écoconstruit ou pas ? À mettre dans la bulle d'aide
    * m² bulle d'aide Loi carrez, tant pis pour les combles
    * Kiffe trop l'aide à la réponse sur l'élec en €, il faut en faire d'autres.
    * "J'achète fréquemment du neuf"
    * Moins de dix ans souligné en jaune ?
    * Électroménager, moins de 10 ans différent de j'en ai pas, perturbe
    * Tondeuse *de jardin*, pas à barbe
    * Emoji internet conso à ajouter
    * Comment ça <- "ça vous hors d'atteinte" ?
    * Arrondi 4 tonnes -> 3,7 pas compris. Mettre le décile en petit ?
    * Barre d'avancement pas complète alors que la simulation est terminée 
    * Actions : déjà fait / je veux le faire / pas possible, animation sympa, vert bleu rouge
    * Liste d'action guidée pas pertinente pour fred, des trucs inutiles tout en haut, il en a fait une partie déjà, etc.
    * Grisé : pas envie de le voir. Vert coché déjà peut-être, ou "afficher les actions non pertinentes pour vous"
    * Bouton partager pas assez visible du tout, il ne l'a pas vu, mais a vu le bandeau action. Mettre deux gros boutons sur la même ligne ?
    * faut que je décoche l'électroménager ?

**Comment by Benjamin-Boisserie-ABC** [comment]
Retour utilisateur de notre assistante à l'ABC :
 - message d'info au début pour indiquer le temps que prend le test ainsi que les "documents" dont on peut avoir besoin
 - rajouter une bulle d'information pourquoi on demande l'age des appareils numériques
 - rajouter chaine hifi et petits enceinte portative dans les équipements numériques 
 - trouve de manière générale qu'on ne dit pas assez ce qui est négatif dans nos comportements et ce qu'il faut donc changer
 - il manque selon elle l'évaluation de l'impact des livraisons UBER, livraison via internet, consommation et téléchargement internet.

Il faut garder en tête qu'elle a une empreinte de 4 tonnes ce qui me fait dire qu'il faut réellement un message qui, pour les utilisateurs qui sont à 5 tonnes ou en dessous, dirait "si vous êtes en dessous des 5 tonnes vous avec fait une grande partie du chemin"

Concernant le message sur le temps et les documents nécessaires je mettrai qqch du type "si vous avez ces données (puis les lister) à disposition vous répondrez plus facilement à certaines questions mais si vous ne les avez pas ce n'est pas grave car le but de NGC est de fournir un ordre de grandeur de votre empreinte carbone et non pas une estimation au dixième prêt"
