### ISSUE TITLE
Publier sur une page l'intégralité du modèle climat NGC

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#308]
Aujourd'hui nous avons la visualisation en mode wikipedia, avec des liens dans tous les sens.

Pour accrocher les gens sur les apports du modèle NGC, il serait bon de pouvoir l'afficher sur une page Web à scroller.

Aujourd'hui on a ça, mais c'est technique : https://ecolab-data.netlify.app/co2.json

Nous avons aussi ça, mais c'est peu intéressant : https://nosgestesclimat.fr/documentation

Il pourrait s'agir d'une nouvelle vue de la documentation dans https://github.com/betagouv/publicodes

@mquandalle @johangirod

**Comment by johangirod** [comment]
Comment verrait-tu cela ? On peut imaginer une page d'accueil éditorialisée des règles publicodes, avec un champs de recherche pour accéder aux règles précises, cela ressemble à https://nosgestesclimat.fr/documentation, mais à améliorer.

On peut imaginer dans ce sens mettre en avant les grands espaces de nom de premier niveau depuis la page d'accueil. Ou encore mettre en avant les règles enfant lorsque la règle parent n'a pas une formule de type numérique.

Pas sûr qu'il soit nécessaire d'avoir une nouvelle vue de la documentation cependant, à moins que je n'ai pas bien cerné le cas d'usage.

**Comment by laem** [comment]
Mon idée (je crois) était de tester l'affichage de tout un nom de domaine sur une seule page.

Dans ce mode, par exemple si tu vas voir https://nosgestesclimat.fr/documentation/transport/avion tu aurais l'ensemble des calculs de ce nom de domaine affichés avec des liens vers le reste de la documentation, mais des liens internes pour toutes les variables du domaine "avion". 

Mais franchement, ce n'est qu'une idée et elle peut s'avérer désastreuse. 

J'aime bien ton idée aussi de simplement faire une meilleure page documentation, éditorialisée.

**Comment by Clemog** [comment]
Je relis cette issue à https://github.com/betagouv/publicodes/pull/250 :)

**Comment by laem** [comment]
Lié à #484

**Comment by jeannelf** [comment]
a garder en tete dans les amelios a venir de la doc
