### ISSUE TITLE
Déclinaison pour d'autres métriques d'empreinte environnementales

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#309]
Cette étude récente très intéressante, elle s'attache à la question de l'énergie plutôt que du climat : https://www.sciencedirect.com/science/article/pii/S0959378020307512#b0005

Voir notamment les "supplementary materials" 

https://ars.els-cdn.com/content/image/1-s2.0-S0959378020307512-mmc1.docx
[1-s2.0-S0959378020307512-mmc1.docx](https://github.com/datagir/nosgestesclimat/files/6783946/1-s2.0-S0959378020307512-mmc1.docx)

![Capture d’écran du 2021-07-08 13-01-32](https://user-images.githubusercontent.com/1177762/124911067-a2b55200-dfec-11eb-895a-04bf2c446cb4.png)

![Capture d’écran du 2021-07-08 13-02-01](https://user-images.githubusercontent.com/1177762/124911112-b19c0480-dfec-11eb-8bf8-3c59f06bb8a7.png)

**Comment by laem** [comment]
En particulier, ça n'implique pas forcément de faire tout ça sur nosgestesclimat.fr. Ce dernier pourrait simplement être utilisé comme un moyen de récupérer des données utilisateur. Pour n'importe quelle métrique environnementale, on aura besoin de savoir combien de steaks les gens mangent. NGC a déjà demandé tout ça à l'utilisateur. 

Le test "eau" demanderait simplement des questions supplémentaires.

**Comment by jeannelf** [comment]
premiere brique faite ✅  a suivre pour la suite !
