### ISSUE TITLE
CGU - politique de confidentialité - mentions légales

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#311]
À intégrer sur le site.

- [x] convertir en markdown les parties nécessaires à piocher dans ces 3 documents
- [x] afficher les fichiers markdown aux endroits adéquats 
- [x] [[Nosgestesclimat]_-_Mentions_légales.docx](https://github.com/datagir/nosgestesclimat-site/files/6809205/Nosgestesclimat._-_Mentions_legales.docx)
- [x] [[Nosgestesclimat]_-_Politique_de_confidentialité.docx](https://github.com/datagir/nosgestesclimat-site/files/6809206/Nosgestesclimat._-_Politique_de_confidentialite.docx)
- [x] [[Nosgestesclimat]_-_CGU.docx](https://github.com/datagir/nosgestesclimat-site/files/6809207/Nosgestesclimat._-_CGU.docx)
- [ ] Poser la ou les bonnes questions à l'équipe juridique

Pour la fonction "sondage", il faudra invoquer la production de statistiques publiques.

Sera réalisé dans #444

**Comment by Clemog** [comment]
A implémenter avec la PR sondage ? #420

**Comment by laem** [comment]
Voici les interrogations qui me restent pour nos amis juristes. 

- Les pages légales sont-elles suffisamment claires sur le fait que nous produisons des données anonymes d'intérêt public, et donc que l'utilisateur ne peut pas nous demander de supprimer sa ligne dans notre base de données ? 
- Jusqu'où peut-on aller dans le stockage des données, des grandes catégories bien larges au détail de 50 questions concernant la vie de l'utilisateur, dans le cadre juridique français ? 
- En particulier, en sachant que ces données seront publiques ?

**Comment by Clem-mrtn** [comment]
A date pas de nouvelles de Thomas 
**=> relancer dans deux semaines**

**Comment by laem** [comment]
Relancé :heavy_check_mark:

**Comment by Clem-mrtn** [comment]
[EDL_Nosgestesclimat_21042022.docx](https://github.com/datagir/nosgestesclimat-site/files/8542240/EDL_Nosgestesclimat_21042022.docx)

Je me permet d'uploader le travail de Laura pour le lier à ce ticket !
Je partage, pour moi l'option 2 est vraiment la plus pertinente. 
Et du coup ce que je comprends c'est que de notre côté, ce qui est actionnable c'est : 

- [ ] Être plus transparent sur le partage des résultats avec les modes conférence & sondage
- [ ] Afficher un message qui averti l'usager que les résultats vont être stockés anonymement 
- [ ] Permettre de stocker les résultats aux questions sans connecter à l'adresse IP sur Matomo

**Comment by Clem-mrtn** [comment]
Suite au retour de Laura : pas d'actions aujourd'hui de notre côté, tout est expliqué dans la partie "Vie Privée" => https://nosgestesclimat.fr/vie-priv%C3%A9e

Si évolutions : retenue "l'option 3" : 
> "- Le détail des réponses par utilisateur : dans cette situation, même si on ne relie pas directement un utilisateur aux réponses, il y a de fortes chances de pouvoir réidentifier une personne car on a accès à l’ensemble de ses réponses. A noter que l’utilisateur peut toutefois « passer » les questions auxquelles il ne souhaite pas répondre, ou choisir une réponse générique proposée par la plateforme, ce qui compliquerait des potentielles réidentifications."

**Comment by Clemog** [comment]
Les docs dans le commentaie en en-tête sont gardés qque part ?

**Comment by jeannelf** [comment]
yes je les ai migrés dans un notion https://www.notion.so/accelerateur-transition-ecologique-ademe/Mentions-Legales-CGU-7a9ae344278046e18d6d649259e363c3?pvs=4
