### ISSUE TITLE
Safari sur iphone ne fonctionne pas

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#335]
Reste à savoir quelle version pose problème. Vraiment obsolète ? Ou plutôt récente ?

**Comment by Clemog** [comment]
Le site entier ou bien certaines fonctionnalités ?

**Comment by laem** [comment]
Ça rejoint notre discussion sur les version safari. Les anciens sont très peu utilisées, CF statscounter.com. Je ferme, c'est vieux.

**Comment by laem** [comment]
iPhone X cassé. 
Du à des fonctionnalités JS toujours pas supportées par Safari. Voir éventuellement les paquets babel, ainsi que la query qu'on fait dans package.json pour le support des navigateurs.
