### ISSUE TITLE
Comparer les résultats à la distribution des français

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#36]
La moyenne peut être trompeuse.

Étudier cette étude de l'OFCE : https://www.agefi.fr/sites/agefi.fr/files/fichiers/2020/01/taxe_aux_frontieres_ofce_paul_maliet.pdf
Autres : 
![image](https://user-images.githubusercontent.com/1177762/82901226-f2a69600-9f5d-11ea-904d-27f42d04f255.png)

https://www-cdn.oxfam.org/s3fs-public/file_attachments/mb-extreme-carbon-inequality-021215-fr.pdf

un article rapide qui mentionne l’étude de Piketty & Chancel (pour ceux qui tombent sur ce thread)
https://www.liberation.fr/checknews/2019/11/06/est-il-vrai-qu-en-france-les-10-les-plus-riches-emettent-huit-fois-plus-de-co2-que-les-10-les-plus-p_1761604

![image](https://user-images.githubusercontent.com/1177762/82901365-1c5fbd00-9f5e-11ea-839d-e06fdc563f33.png)

Merci les bénévoles du Shift pour ces sources :)

_Originally posted by @laem in https://github.com/betagouv/ecolab-climat/issues/4#issuecomment-633955320_

**Comment by laem** [comment]
@jeremiecook

**Comment by jeannelf** [comment]
A traiter 
https://www.notion.so/accelerateur-transition-ecologique-ademe/Page-de-fin-Se-comparer-la-moyenne-distribution-des-fran-ais-af6eb8a8e3b54855a68644c5a1626d7b?pvs=4
