### ISSUE TITLE
Problèmes remontés par Google search console

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#489]
Je découvre cette page. Notre score est très mauvais. 

![image](https://user-images.githubusercontent.com/1177762/159753772-026796cc-ef24-4068-b138-e96db15ded41.png)

**Comment by Clemog** [comment]
MAJ suite à la PR #478 @laem ?

**Comment by laem** [comment]
On reste toujours très mauvais à mon avis. Il y a un taf spécifique à faire, prioritaire pour le SEO, mais pas forcément trop compliqué.

**Comment by laem** [comment]
Un gros boulot a été fait, mais la perf des pages qui instantient le moteur reste mauvaise. Voir https://github.com/datagir/nosgestesclimat/pull/1502

**Comment by jeannelf** [comment]
grosse amélio sur [pagespeed](https://pagespeed.web.dev/analysis/https-nosgestesclimat-fr/yfx2wa81gc?form_factor=desktop) , en revanche on garde à l'oeil la rapidité des pages selon l aGSC
