### ISSUE TITLE
Enregistrer ses données du Bilan sur son PC (Firefox)

### ISSUE THREAD

**Issue by jrd10** [incubateur-ademe/nosgestesclimat-site#534]
Bonjour, félicitations et merci de cet outil. 

Je comprends que les données sont stockées dans le navigateur.

Existe-t-il un moyen de les sauvegarder dans un fichier qui pourra être réimporté ultérieurement ?
Comme avec les Bookmarks :).

Pour tester plusieurs configurations, je vais utiliser Firefox Multi-Account Containers :).

Merci de votre temps,

Amicalement, José

**Comment by laem** [comment]
Si ça vous intéresse, vous pouvez en attendant voir aussi l'issue #400
