### ISSUE TITLE
Afficher le DPE ?

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#538]
Article très intéressant sur la réforme du DPE en juillet 2021

https://www.capital.fr/immobilier/immobilier-voici-les-principales-evolutions-du-nouveau-diagnostic-de-performance-energetique-1394146

En gros, le diagnostic de performance énergétique, est maintenant (2022) obligatoire pour toute transaction immobilière et location, et surtout **opposable**. En bref ça veut dire que si le vendeur dit à l'entrepreneur "ouais mettez pas les fuites d'air de mes fenêtres là je vais corriger ça bientôt", il ne s'exécutera pas de peur d'être attaqué par l'acheteur. 

Autre changement de taille, il est maintenant **théorique**, basé sur les caractéristiques réelles du bâti plutôt que sur les factures de l'ancien locataire. Un logement chauffé à 16° pouvait donc avoir un bon DPE malgré son caractère de passoire thermique. 

Troisième changement de taille, le DPE est maintenant la note minimum (de A à G) de deux indicateurs, énergie et climat. Ainsi, un logement au gaz aura un mauvais DPE même si bien isolé, et un logement élec (bas carbone en France) aura un mauvais DPE si mal isolé. 

Ce que nous pourrions faire dans NGC, c'est afficher à l'utilisateur son DPE d'usage, donc ancienne méthode. Vous me direz que c'est anachronique : oui, mais néanmoins très intéressant à mon avis, en l'absence des informations nombreuses nécessaires pour calculer le DPE théorique. Il y aurait justement un intérêt à lui montrer ce DPE d'usage pour qu'il le compare à un éventuel ou futur DPE théorique, ne serait-ce que pour introduire le sujet et le pousser à se renseigner sur les changements législatifs aux conséquences énormes qui arrivent, comme en témoigne cet article récent du Monde. 

https://www.lemonde.fr/societe/article/2021/12/27/diagnostic-de-performance-energetique-panique-dans-le-secteur-de-l-immobilier_6107371_3224.html#xtor=AL-32280270-[default]-[ios]

[Nouveau diagnostic de performance énergétique panique dans le secteur de l’immobilier(1).pdf](https://github.com/datagir/nosgestesclimat/files/7802896/Nouveau.diagnostic.de.performance.energetique.panique.dans.le.secteur.de.l.immobilier.1.pdf)

On peut utiliser des librairies déjà faites, voir y contribuer :)  https://www.npmjs.com/package/react-dpe-generator

![image](https://user-images.githubusercontent.com/1177762/147956003-777ea829-fc0b-4b05-9eff-8a85641a306a.png)

Démo ici, c'est tout simple : https://codesandbox.io/s/happy-cerf-rtj1l

**Comment by jeannelf** [comment]
https://www.notion.so/accelerateur-transition-ecologique-ademe/Food-for-thought-DPE-logement-205f507fd0ac433f8a434e82a0436f92
