### ISSUE TITLE
Slide 5 du tuto affichée différemment ?

### ISSUE THREAD

**Issue by Clemog** [incubateur-ademe/nosgestesclimat-site#617]
Beaucoup de personnes ignorent le tuto avant la dernière slide, or il semble qu'elle est particulièrement importante et comporte des informations de nature différente .. 
J'imagine que ce contenu pourrait apparaître dans un petit onglet "astuces" .. Je n'ai pas forcément d'idée sur sa position

**Comment by laem** [comment]
Il faut potentiellement forcer le visionnage du tuto. 
C'est une possibilité à considérer à mon avis. Si on affiche ces infos ailleurs, sans les forcer, il y a de grandes chances que ce ne soit pas davantage consulté.

**Comment by mquandalle** [comment]
À mon humble avis, la position actuelle du bouton « passer le tutoriel » c'est celle to “call to action” naturel une fois qu'on a fini de lire la carte. Un bouton « SUIVANT » à cet endroit serait sans doute efficace.

![image](https://user-images.githubusercontent.com/1730702/186225383-2b3d6fc4-b859-4a4f-8428-3d2d0d7b559b.png)

**Comment by laem** [comment]
Oui, ça pourrait être une croix plus discrète.

**Comment by JeanPaulGrange** [comment]
Pour information lorsque je rentre sur l'application depuis : https://nosgestesclimat.fr je ne vois pas de tutoriel dont il est question.
Notamment pas de solution pour l'issue [1300](https://github.com/datagir/nosgestesclimat/issues/1300). 
Je vois ce qui est ci-dessous et rien dans la documentation
![Snag_3e82e96c](https://user-images.githubusercontent.com/33667947/186227311-3cf9f8eb-672d-4ae1-b680-496f41696e73.png)

**Comment by laem** [comment]
@JeanPaulGrange le tuto s'affiche lors de ton premier test quand tu cliques sur Faire le test :à

**Comment by JeanPaulGrange** [comment]
> @JeanPaulGrange le tuto s'affiche lors de ton premier test quand tu cliques sur Faire le test :)

@Iaem ça serait bien de garder un lien ensuite car j'ai déjà fait le premier test et arrêté en cours du coup je n'ai plus le tuto.

**Comment by Clemog** [comment]
> > @JeanPaulGrange le tuto s'affiche lors de ton premier test quand tu cliques sur Faire le test :)
> 
> @laem ça serait bien de garder un lien ensuite car j'ai déjà fait le premier test et arrêté en cours du coup je n'ai plus le tuto.

@JeanPaulGrange tu peux le retrouver en allant sur "Mon Profil", il y a un bouton "Revoir le tutoriel" mais si tu ne le trouves pas alors que tu as cherché, on doit peut-être imaginer une autre manière de le montrer ..

Pour donner quelques inputs à la discussion, sur la semaine dernière :

![image](https://user-images.githubusercontent.com/55186402/186609193-648f694a-a991-4d5f-854e-f0785e60475b.png)

![image](https://user-images.githubusercontent.com/55186402/186609555-cf9232bc-1dbf-4d6d-a432-cd538633e9c5.png)

**Comment by Clemog** [comment]
je me dis qu'on pourrait afficher la slide 5 quoiqu'il arrive : si 'l'utilisateur ignore le tuto, il tombe sur la page 5 ?

**Comment by laem** [comment]
Suggestion intéressante ! Mais je me demande s'il ne faut pas, plus simplement, forcer le tuto ?

**Comment by Clemog** [comment]
En laissant la possibilité d'ignorer, on sait qui a vraiment ignoré le tuto via le tracking

**Comment by laem** [comment]
On peut faire un mélange : 
- la suggestion de maxime : mettre en retrait le bouton "passer le tuto"
- obliger la slide 5

**Comment by lbranaa** [comment]
@jeremiecook : issue à lire pour le travail sur le tuto :)
