### ISSUE TITLE
Exposer sur le site toutes les issues github

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#644]
Je me demande si tout ce contenu accumulé depuis 2 ans ne pourrait pas être mis en ligne sur nosgestesclimat.fr. 
Google indexe github, mais c'est github qui récupère ce karma. Google en redirige une partie vers ngc, mais impossible de savoir combien. 
Cela pourrait être sur une page contribution, qui permettrait de faire une recherche dans le contenu des issues sans aller sur github. 
À investiguer.

**Comment by laem** [comment]
Je pense que ce serait peut-être une erreur de faire ça. 
Par contre, ce qu'on doit garder en tête, c'est que tout le contenu intéressant des issues **doit** être mis dans la documentation. Il y a un tas de choses qu'on n'expose pas aujourd'hui. 

Exemple avec mon issue récente sur le biogaz. 

Peut-être qu'on pourrait exposer seulement les issues ayant un ou des tags précis ? 

@Clemog @EmileRolley

**Comment by EmileRolley** [comment]
Dans un premier temps je pense qu'il suffirait de rajouter deux liens:

```
https://github.com/datagir/nosgestesclimat{-site}/labels/<label>
```

Où `<label>` permettrait de tagger toutes les issues que l'on estime être intéressantes à partager avec les utilisatrices et les utilisateurs.

**Comment by laem** [comment]
Oui on peut décider d'un label, mais rediriger vers github transferera le SEO à github, donc ça ne répond pas au sujet initial de ce ticket.
