### ISSUE TITLE
Étendre à d'autres pays 🇨🇫

### ISSUE THREAD

**Issue by laem** [incubateur-ademe/nosgestesclimat-site#71]
Reposer sur une asso / agence locale à un autre pays, qui connaît les différences. 
Via Tomorrow, on peut avoir des contacts Danois. Via les Shifters, j'ai des contacts Belges 🙂

**Comment by leroyvn** [comment]
Salut @laem, je suis membre des Shifters Belgique et je suis super intéressé par le simulateur. C'est un excellent complément à nos conférences de sensibilisation grand public. On a du monde pour contribuer, je suis de près l'évolution de l'outil.

**Comment by laem** [comment]
Bonjour @leroyvn ! Est-ce que dans un premier temps on pourrait se limiter à la Belgique francophone ?

**Comment by leroyvn** [comment]
Tout à fait, les Shifters belges sont de toute manière majoritairement francophones.

**Comment by laem** [comment]
Super. Vous vous êtes penchés sur le modèle de calcul (sur betagouv/ecolab-data) pour identifier les facteurs d'émission à changer ? 
Comme ça, je pense que changer le facteur du mix électrique, dans `logement.yaml` ferait déjà 80% du boulot :) 

On a alors 2 solutions : 
- soit ouvrir l'URL officielle aux Belges en posant la question "Dans quel pays faire la simulation"
- soit paramétrer le pays dans l'URL d'intégration de l'iframe, pour que vous l'intégriez sur un site en .be adressé uniquement aux Belges

**Comment by leroyvn** [comment]
Je vais voir ça, un shifter bruxellois a fait une version localisée du MicMac Excel et on va partir de ça. Comme on dit ici, je te dis quoi :)

Pour l'accès, il y a déjà dans le simulateur une façon de changer de base de données dynamiquement ? Comme [ici](https://github.com/betagouv/ecolab-data/blob/master/CONTRIBUTING.md#si-vous-voulez-participer-%C3%A0-lam%C3%A9lioration-du-mod%C3%A8le) mais en pointant vers un fork ?

**Comment by laem** [comment]
Non, tu ne peux changer la base de règles (le yaml) que pour une PR ou une branche de ecolab-data

A moins que vous ayez du temps de dev devant vous (quelqu'un à minimum un jour par semaine sur au moins 6 mois, pour faire des ajouts de fonctionnalité), il vaut mieux pas forker. Mieux vaut qu'on trouve un moyen de faire cohabiter les deux bases sur le même dépôt.

**Comment by laem** [comment]
>  Comme ça, je pense que changer le facteur du mix électrique, dans logement.yaml ferait déjà 80% du boulot :)

A vrai dire, je crains que ça ne soit pas aussi simple. Nous utilisons des facteurs d'émission "finaux", par exemple l'empreinte des voitures électriques à l'usage, qui est pré calculée et publiée dans la base bilan-GES de l'ADEME. C'est un problème, car si on avait à la place la conso en kWh des VE, l'empreinte changerait en fonction du mix électrique des pays en un clic (quitte à utiliser non pas une moyenne du mix mais une empreinte pertinentes aux VE : on roule rarement la nuit). 

Cela dit, rien n'empêche d'avancer par petits pas, et de corriger tout cela au fur et à mesure. Je crois que les Belges ont une empreinte par personne de 15 tonnes, significativement plus élevée que les Français. Au-delà du mix électrique, cela révèle sûrement des plus grosses voitures, des plus gros logements, etc. Cela influe les valeurs par défaut, mais ce n'est pas très grave, chacun peut justement renseigner la taille de la voiture qu'il utilise.

**Comment by laem** [comment]
Ce sujet revient régulièrement. Voir ce fil twitter avec des expressions d'intérêt :) 

https://twitter.com/maxlambr/status/1409421388084097024

**Comment by laem** [comment]
Petite mise à jour de ce sujet : nous avons tenté d'obtenir un financement de l'État pour lancer ce sujet de l'internationalisation, mais notre proposition n'a pas été retenue. 

Cela ne veut pas dire que nous n'allons pas lancer ce chantier, mais le calendrier reste donc à préciser. 

Les expressions d'intérêt continuent de plus belle, avec ici un travail d'adaptation du modèle transport pour l'outre-mer français :arrow_down: 

https://github.com/datagir/nosgestesclimat/issues/1341

**Comment by laem** [comment]
Je remarque que le premier résultat Google de cette recherche, c'est NGC. Gros intérêt pour l'i18n !

![image](https://user-images.githubusercontent.com/1177762/187472163-0d8b9ad5-40f0-4e0b-acff-4570627a5ae8.png)

**Comment by laem** [comment]
Ne pas oublier de transformer certaines questions pour l'international https://github.com/datagir/nosgestesclimat/issues/1593
