### ISSUE TITLE
Ajouter deux questions pour mesurer l'impact

### ISSUE THREAD

**Issue by lbranaa** [incubateur-ademe/nosgestesclimat-site#894]
A la fin du test : 
- [x] "Dans quelle mesure Nos Gestes Climat vous a appris quelque chose ?" --> échelle de 1 à 4 étoiles

Après les actions : 
- [x] "Dans quelle mesure Nos Gestes Climat vous donne envie d'agir pour réduire votre empreinte carbone ?" -> échelle de 1 à 4 étoiles

A voir si on le met sous forme de pop-up

**Comment by laem** [comment]
Quelques remarques sur les questions. 

1) Je me permets le pari qu'on aura un bon score (mais ça reste bien de le vérifier :+1: ), 70-90%. 

Mais du coup je me demande les actions qui sont déclenchées par ce score. S'il est de 70-90%, on en conclut que tout va bien ? S'il est de 50%, qu'est-ce que ça remet en question ? Ça me semble important d'y réfléchir en amont. 

Quelles informations, quels indices nous donneraient une réponse négative ? Qu'il faut davantage travailler la pédagogie ? Ou que nos utilisateurs sont déjà sensibilisés à force ? Qu'ils sont le 1% très éduqué ? Qu'este-ce qu'une réponse négative ?

**Comment by margauxcoco** [comment]
1. Je suis d'accord avec tes remarques. D'après moi, on atteint l'impact si les personnes répondent 3 ou 4. Et pour l'interprétation des réponses négatives, il faudrait clairement prévoir des tests utilisateurs pour avoir plus de retours quali ensuite si on se rend compte qu'il y en a beaucoup.

Par ailleurs, pour la première question, on pourrait aussi penser à une question plus 'précise' du type : 'Sur une échelle de 1 à 4, dans quelle mesure NGC vous a permis de nourrir votre compréhension de l'empreinte carbone et de vos principales sources d'émission ?'

2. Pour la seconde question, selon moi ça dépend si on veut du quanti ou du quali. Si c'est le premier, je trouve la question bien ; si c'est le second, on pourrait imaginer une autre formulation avec plusieurs options à reformuler ensuite ensemble et à cocher du type :
'Le test et vos résultats Nos Gestes Climat :

- ne vous procure aucune réaction
- vous décourage de tout changement de comportement
- vous choque
- vous donne envie d'agir sans savoir comment
- vous donne envie d'agir et vous donne les clefs pour le faire
- autre réaction - précisez

**Comment by lbranaa** [comment]
Point supplémentaire : ici, on veut mesurer en valeur absolue et pas seulement en pourcentage. Notre objectif = faire augmenter en valeur absolue le nombre de personnes qui répondent 3 ou 4

**Comment by claireduizabo** [comment]
Je rebondis sur les messages de Margaux et Laurène, avec lesquels je suis complètement d'accord.

Je suis notamment en phase avec la proposition de Margaux d'avoir une évaluation sur l'état qu'on déclenche chez les testeurs - pour la question 2. 
Je trouve que c'est original et que c'est une façon de bien palper l'impact : l'évolution du nombre de personnes qui répondent 'vous donne envie d'agir et vous donne les clefs pour le faire' fera de la data intéressante à suivre

**Comment by dxb** [comment]
Je propose plusieurs approches pour stocker le résultats à ces questions :

- dans matomo (ou plausible), comme objectif. Cela permettrait de filtrer ces résultats par type de périphérique par exemple, pour tirer des enseignements sur les ressentis dans différents formats.
- dans la base mongodb, c'est simple et efficace, à condition d'avoir une interface de consultation comme metabase.

**Comment by lbranaa** [comment]
Je ferme car c'est fait !
