### ISSUE TITLE
Migrate scripting files to TS

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#899]
Currently, scripting file are plain Node.js. However, as they start to be complex, having type will facilitate their maintenance.

**Comment by lbranaa** [comment]
Tu peux décrire mieux le problème ? Merci :)

**Comment by EmileRolley** [comment]
Non je pense qu'en effet, avoir une générique comme cela n'apporte pas grand chose.
