### ISSUE TITLE
Questionnaire : suggestions d'améliorations pour la barre de progression

### ISSUE THREAD

**Issue by bjlaa** [incubateur-ademe/nosgestesclimat-site#927]
J'ai relevé quelques points qui m'ont gêné dans cet élément :
* quand on arrive sur le questionnaire, on peut changer de section du questionnaire en cliquant sur chaque partie de la barre affichée. Quand on démarre le questionnaire, une nouvelle barre s'affiche mais le comportement est différent et crée un incohérence : quand on clique dessus le détail du pourcentage s'affiche. Peut prêter à confusion pour nos utilisateurs.
* Le titre de la section en cours est affiché au dessus de cet élément mais en dessous du bloc formulaire, ne devrait-il pas être affiché au dessus ?
* j'ai l'impression que la barre de progression serait plus à sa place au dessus du formulaire et pourrait donc faire office de fil d'ariane (++SEO)
* il n'y a pas de point de repère sur la barre de progression pour savoir à quelle étape on en est ; par ailleurs, je trouve qu'il manque une mention de la sous section du questionnaire en cours dans le titre, par exemple "Transports : l'empreinte carbone de vos trajets en voiture"
* le composant me parait un peu imposant et gagnerait à être réduit en taille pour gagner un peu d'espace et en hiérarchisation des éléments de cette page

Proposition (faite en bidouillant dans la console navigateur) :
<img width="1440" alt="Capture d’écran 2023-04-05 à 11 26 38" src="https://user-images.githubusercontent.com/12382534/230041109-e287c2bf-b254-4abc-9364-29c1f110e528.png">

**Comment by laem** [comment]
> quand on arrive sur le questionnaire, on peut changer de section du questionnaire en cliquant sur chaque partie de la barre affichée. Quand on démarre le questionnaire, une nouvelle barre s'affiche mais le comportement est différent et crée un incohérence : quand on clique dessus le détail du pourcentage s'affiche. Peut prêter à confusion pour nos utilisateurs.

Oui, je pense aussi qu'il faudrait pouvoir naviguer de sous-section en sous-section également. Le problème aujourd'hui, c'est que faute de #762, elles sont souvent très mal cadrées. 

> Le titre de la section en cours est affiché au dessus de cet élément mais en dessous du bloc formulaire, ne devrait-il pas être affiché au dessus ?

C'était le cas avant. En gros ton design correspond à l'une des itérations de la page conversation, avec le titre et graphique de sous-catégories en haut, et le graphique des catégories en bas. On s'est dit qu'il fallait rapprocher les deux, la distance étant perturbante ; et que l'important pour l'utilisateur, c'est de répondre aux questions, une par une, le reste étant secondaire. À mon avis ça tient toujours, l'important c'est les questions. 

À ce moment là, le graphique de catégorie en ligne n'était pas implémenté.

**Comment by laem** [comment]
> j'ai l'impression que la barre de progression serait plus à sa place au dessus du formulaire et pourrait donc faire office de fil d'ariane (++SEO)

Oui à vrai dire ce n'est pas une barre de progression. Nous avions une barre de progression tout en haut, en % du test, mais elle a été déplacée dans le bouton du menu... mais ne s'affiche plus pour des questions de performance (il faut pouvoir afficher le menu sans avoir parsé les règles).

**Comment by bjlaa** [comment]
> C'était le cas avant. En gros ton design correspond à l'une des itérations de la page conversation, avec le titre et graphique de sous-catégories en haut, et le graphique des catégories en bas. On s'est dit qu'il fallait rapprocher les deux, la distance étant perturbante ; et que l'important pour l'utilisateur, c'est de répondre aux questions, une par une, le reste étant secondaire. À mon avis ça tient toujours, l'important c'est les questions.
Je vois ! Ça fait sens, je retire ma suggestion. :) 
En revanche, j'ai quand même l'impression qu'un quick-win sympa pour les utilisateurs serait d'afficher le titre au dessus du questionnaire, en titre du formulaire avec dynamiquement une partie du titre qui se met à jour en fonction de la catégorie : 
<img width="1440" alt="Capture d’écran 2023-04-06 à 11 38 09" src="https://user-images.githubusercontent.com/12382534/230339904-389c6bf8-c8f9-49a1-b698-b0e33854f1d2.png">

> On s'est dit qu'il fallait rapprocher les deux, la distance étant perturbante
Ici tu parlais du titre et de la barre de catégories / progression ? Si c'est le cas je me demande en quoi c'est perturbant 🤔 au contraire j'ai l'impression que ça donne un cadre à l'utilisateur qui est plus accompagné dans son expérience.
