### ISSUE TITLE
Tests e2e v2

### ISSUE THREAD

**Issue by EmileRolley** [incubateur-ademe/nosgestesclimat-site#965]
To follow up #901, several improvements could be made sorted by priority:

* [x] #984 
* [x] #979
* [x] #1003
* [ ] Have an exhaustive cover up of the sitemap (e.g. documentation pages)
* [ ] Test group mode?
* [ ] Test actions?

**Comment by florianpanchout** [comment]
Les tests e2e sont loin d'être complets mais je crois qu'on a déjà une carte Notion la dessus
